"""G-Code zurücklesen (Bauplan §28.1, §28.2).

Die Schichtanalyse (§22) sucht und beurteilt; der externe Slicer liefert die
Wahrheit für die Datei, die zum Drucker geht. Dieses Modul liest diese Wahrheit
zurück: Druckzeit, Material, **gemessenes** Stützvolumen, Schichtzahl,
Warnungen.

Das Verhältnis ist herum, wie §28.2 es beschreibt. Die Suche läuft intern über
hunderte Kandidaten; der externe Lauf bestätigt den Gewinner und liefert die
Kostenschätzung. Das hier ist also kein zweiter Slicer, es ist die
Endabnahme.

Jede Zahl, die hier herauskommt, trägt ``source="gcode"`` und wird nie mit
einer internen Schätzung vermischt (§22.5). Wo die zwei um mehr als ein
Sechstel auseinanderliegen, ist das ein Befund — und ein Hinweis, dass die
Schichtanalyse Arbeit braucht, kein Grund, eine von beiden still vorzuziehen.
"""

from __future__ import annotations

import re
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field

from app.core.log import get_logger
from app.core.types import BoundingBox, Finding, MetricSource
from app.i18n import _

_log = get_logger(__name__)

#: Über diesem relativen Unterschied wird die Gegenprobe ein Befund (§28.2).
DEVIATION_LIMIT = 0.15

#: Dichte der üblichen Filamente in g/cm³ — für das Gewicht aus der Länge.
DEFAULT_DENSITY = 1.24

#: Querschnitt eines 1,75-mm-Filaments in mm².
FILAMENT_AREA = 2.405


@dataclass(slots=True)
class GcodeMetrics:
    """Was eine geslicete Datei über sich selbst sagt.

    Alles optional: Slicer schreiben verschiedene Kommentare, und ein
    fehlender Wert fehlt — er ist nicht null. Genau diese Unterscheidung ist
    der ganze Grund, die Datei zu lesen statt aus ihr zu raten.
    """

    slicer: str = ""
    print_seconds: float | None = None
    filament_mm: float | None = None
    filament_grams: float | None = None
    support_mm3: float | None = None
    layer_count: int | None = None
    layer_height: float | None = None
    warnings: tuple[str, ...] = ()
    source: MetricSource = "gcode"

    @property
    def print_minutes(self) -> float | None:
        return None if self.print_seconds is None else self.print_seconds / 60.0

    @property
    def material_cm3(self) -> float | None:
        """Filamentlänge als Volumen — die Größe, die mit der Schätzung
        vergleichbar ist.
        """
        if self.filament_mm is None:
            return None
        return self.filament_mm * FILAMENT_AREA / 1000.0

    def grams(self, density: float = DEFAULT_DENSITY) -> float | None:
        # Nur ein Gewicht über null ist eine Messung — dieselbe Absicherung,
        # die `filament_mm` seit dem Cura-Vorfall hat: dessen Kopf schreibt
        # die Werte, *bevor* gerechnet wird, und eine Null gälte sonst als
        # perfekte Übereinstimmung.
        if self.filament_grams is not None and self.filament_grams > 0.0:
            return self.filament_grams
        volume = self.material_cm3
        return None if volume is None else volume * density


#: Kommentarzeilen, die die verbreiteten Slicer schreiben. Ein Muster je
#: Tatsache, nicht ein Parser je Slicer: ein neuer Slicer braucht meist nur
#: eine weitere Zeile hier.
_PATTERNS: tuple[tuple[str, str], ...] = (
    ("print_seconds", r";\s*estimated printing time.*?=\s*(?P<value>[0-9hmsd ]+)"),
    ("print_seconds", r";\s*TIME:\s*(?P<value>[0-9.]+)"),
    ("print_seconds", r";\s*total print time.*?:\s*(?P<value>[0-9hmsd ]+)"),
    ("filament_mm", r";\s*filament used \[mm\]\s*=\s*(?P<value>[0-9.]+)"),
    ("filament_mm", r";\s*Filament used:\s*(?P<value>[0-9.]+)m\b"),
    ("filament_grams", r";\s*filament used \[g\]\s*=\s*(?P<value>[0-9.]+)"),
    ("layer_count", r";\s*(?:total )?layer count\s*[:=]\s*(?P<value>[0-9]+)"),
    ("layer_count", r";\s*LAYER_COUNT:\s*(?P<value>[0-9]+)"),
    ("layer_height", r";\s*layer_height\s*=\s*(?P<value>[0-9.]+)"),
    ("layer_height", r";\s*Layer height:\s*(?P<value>[0-9.]+)"),
    ("slicer", r";\s*(?:generated by|Generated with)\s*(?P<value>.+)"),
)

_SUPPORT_TOOL = re.compile(r";\s*TYPE:\s*(?P<type>.+)", re.IGNORECASE)
_EXTRUSION = re.compile(r"^G1\b(?=.*\bE(?P<e>-?[0-9.]+))(?=.*\b[XY])", re.IGNORECASE)

#: Eine Bewegung — ``G0`` fährt leer, ``G1`` gerade, ``G2``/``G3`` im Bogen.
#: Die Bogenformen stehen mit dabei, weil eine Kreiswand mit Bogenanpassung
#: **nur** aus ihnen besteht: Wer sie überliest, verliert genau die Ausmaße
#: eines Zylinders.
_MOVE = re.compile(r"^G(?P<code>[0-3])\b", re.IGNORECASE)
#: Die drei Achsen einzeln, in der Reihenfolge X, Y, Z.
_AXES = tuple(re.compile(rf"\b{name}(-?[0-9.]+)", re.IGNORECASE) for name in "XYZ")
#: Die E-Achse ohne die Bedingungen von :data:`_EXTRUSION` — für Bögen, die
#: kein ``G1`` sind.
_E_AXIS = re.compile(r"\bE(-?[0-9.]+)", re.IGNORECASE)
_WARNING = re.compile(r";\s*(?:WARNING|Warnung)[:\s]\s*(?P<text>.+)", re.IGNORECASE)

#: Die Marke, mit der PrusaSlicer jeden Schichtwechsel ankündigt. Gezählt ist
#: sie die Schichtzahl, die er sonst nirgends nennt.
_LAYER_CHANGE = re.compile(r"^;\s*LAYER_CHANGE\s*$", re.IGNORECASE | re.MULTILINE)


def parse(text: str) -> GcodeMetrics:
    """Liest eine G-Code-Datei. Was nicht darin steht, bleibt unbekannt."""
    metrics = GcodeMetrics()
    warnings: list[str] = []

    for name, pattern in _PATTERNS:
        if getattr(metrics, name) is not None and getattr(metrics, name) != "":
            continue
        found = re.search(pattern, text, re.IGNORECASE)
        if found is None:
            continue
        _set(metrics, name, found.group("value").strip())

    for line in text.splitlines():
        found = _WARNING.match(line.strip())
        if found:
            warnings.append(found.group("text").strip())

    # Die letzte Schichtmarke schlägt den Kopf. ``CuraEngine`` schreibt dort
    # ``;TIME:6666`` — eine Vorlage, die im Fenster ersetzt wird und von der
    # Kommandozeile aus stehen bleibt. Sie sieht aus wie eine Zeit (111
    # Minuten), ist aber für jedes Modell dieselbe. Am Ende der Datei steht die
    # gerechnete: gemessen 20,8 Minuten für einen 20-mm-Würfel, gegen 21 bei
    # PrusaSlicer mit denselben Einstellungen.
    elapsed = re.findall(r";\s*TIME_ELAPSED:\s*([0-9.]+)", text, re.IGNORECASE)
    if elapsed:
        metrics.print_seconds = float(elapsed[-1])

    if metrics.layer_count is None:
        # PrusaSlicer nennt die Schichtzahl nirgends im Kopf — er markiert
        # jeden Wechsel. Gezählt sind das dieselbe Auskunft: gemessen hundert
        # Marken für hundert Schichten eines 20-mm-Würfels. Ohne sie stand im
        # Prüfbericht bei jedem Prusa-Lauf nichts, wo bei Cura eine Zahl steht.
        changes = sum(1 for _ in _LAYER_CHANGE.finditer(text))
        metrics.layer_count = changes or None

    total, support = _extruded(text)
    metrics.support_mm3 = None if support is None else support * FILAMENT_AREA
    # Was der Kopf nicht sagt, sagen die Bahnen. Der Kopf hat trotzdem Vorrang:
    # er ist die Aussage des Slicers über seinen eigenen Lauf, und die kennt
    # Vorgänge, die keine Bahn zeigt — Vorschieben, Reinigungsturm,
    # Werkzeugwechsel.
    #
    # Die Null ist dabei keine Aussage. ``CuraEngine`` schreibt den Kopf,
    # **bevor** es rechnet, und füllt „Filament used" im Fenster nachträglich
    # aus; von der Kommandozeile aus bleibt dort eine Vorlage stehen. Solidon
    # meldete deshalb null Meter zu einer Datei, die 1,8 MB Bahnen mit Vorschub
    # enthielt — und der Prüfbericht rechnete Kosten von null.
    if metrics.filament_mm is None or (metrics.filament_mm <= 0.0 and total > 0.0):
        metrics.filament_mm = total or None
    metrics.warnings = tuple(warnings)
    _log.info("read g-code of %s", metrics.slicer or "unknown slicer")
    return metrics


def extrudes(text: str) -> bool:
    """Fördert diese Datei überhaupt Material?

    Format-unabhängig gefragt: nicht am Kommentar, den jeder Slicer anders
    schreibt, sondern an der Bewegung selbst. Eine Datei ohne eine einzige
    Bahn mit Vorschub ist kein Druck — sie ist ein Leerlauf über die Platte,
    und sie entsteht, wenn der Slicer das Modell nicht gefunden oder
    verworfen hat. Groß ist sie trotzdem, und ohne diese Frage sähe sie aus
    wie ein geglückter Lauf.
    """
    return any(_EXTRUSION.match(line) and float(_e_value(line)) > 0.0 for line in text.splitlines())


def printed_extent(text: str) -> BoundingBox | None:
    """Wohin diese Datei wirklich druckt — aus den Bahnen, nicht aus dem Kopf.

    ``None``, wenn keine einzige Bahn Material fördert; dann sagt
    :func:`extrudes` das Nötige.

    **Warum aus den Bahnen.** Dieselbe Überlegung wie bei :func:`extrudes`: Der
    Kopf ist das, was ein Slicer über sich behauptet, die Bewegung ist, was der
    Drucker tut. CuraEngine schreibt in seinen Kopf ``;MINX:2.14748e+06`` — den
    unbesetzten Anfangswert —, weil dort sonst das Cura-Fenster nachträglich
    einträgt; von der Kommandozeile aus bleibt er stehen.

    **Und wozu.** Weil ein Slicer eine Datei schreiben kann, die neben der
    Platte druckt; wer davon nur aus dem Kopf erfährt, erfährt es nie.
    :func:`app.core.export.handover.off_the_bed` beurteilt das Maß, das hier
    herauskommt, und dort steht die Messung.

    Gelesen wird der Absolutwert der Achsen; die Stelle wird über alle
    Bewegungen nachgeführt, auch über die leeren, denn Z steht so gut wie nie
    in derselben Zeile wie die Bahn. Relative Bewegungen (``G91``) kommen in
    Druckdateien für die Platte nicht vor — der Vorschub ja, die Achsen
    nicht —, und wo doch, fehlt ihnen der Bezug: sie werden übersprungen,
    statt eine Zahl zu erfinden.
    """
    position: list[float | None] = [None, None, None]
    lowest = [float("inf")] * 3
    highest = [float("-inf")] * 3
    seen = False
    relative = False
    for line in text.splitlines():
        head = line[:3].upper()
        if head == "G91":
            relative = True
            continue
        if head == "G90":
            relative = False
            continue
        move = _MOVE.match(line)
        if relative or move is None:
            continue
        # Erst die Stelle nachführen, dann fragen, ob dort gedruckt wurde: Z
        # steht so gut wie nie in derselben Zeile wie die Bahn, und ein
        # ``G1 Y30 E0.5`` behält sein X von vorher.
        for axis, pattern in enumerate(_AXES):
            found = pattern.search(line)
            if found is not None:
                position[axis] = float(found.group(1))
        pushed = _E_AXIS.search(line)
        if move.group("code") == "0" or pushed is None or float(pushed.group(1)) <= 0.0:
            continue
        for axis, value in enumerate(position):
            if value is None:
                continue
            lowest[axis] = min(lowest[axis], value)
            highest[axis] = max(highest[axis], value)
            seen = True
    if not seen:
        return None
    # Wo eine Achse in keiner Bahn stand, bleibt der Anfangswert stehen — und
    # daraus wird eine Null, keine Unendlichkeit.
    for axis in range(3):
        if lowest[axis] > highest[axis]:
            lowest[axis] = highest[axis] = 0.0
    return BoundingBox((lowest[0], lowest[1], lowest[2]), (highest[0], highest[1], highest[2]))


def _e_value(line: str) -> str:
    found = _EXTRUSION.match(line)
    return "0" if found is None else found.group("e")


def _set(metrics: GcodeMetrics, name: str, value: str) -> None:
    if name == "slicer":
        metrics.slicer = value
        return
    if name == "print_seconds":
        metrics.print_seconds = _seconds(value)
        return
    number = _number(value)
    if number is None:
        return
    if name == "filament_mm":
        # „Filament used: 3.42m" sind Meter, „filament used [mm] = 3420" nicht.
        metrics.filament_mm = number * 1000.0 if number < 100.0 else number
    elif name == "filament_grams":
        metrics.filament_grams = number
    elif name == "layer_count":
        metrics.layer_count = int(number)
    elif name == "layer_height":
        metrics.layer_height = number


def _number(value: str) -> float | None:
    try:
        return float(value)
    except ValueError:
        return None


def _seconds(value: str) -> float | None:
    """``2h 14m 3s``, ``14m``, oder nackte Sekunden — alles davon kommt vor."""
    plain = _number(value)
    if plain is not None:
        return plain
    total = 0.0
    found = False
    for amount, unit in re.findall(r"(\d+)\s*([dhms])", value.lower()):
        found = True
        total += float(amount) * {"d": 86400.0, "h": 3600.0, "m": 60.0, "s": 1.0}[unit]
    return total if found else None


def _extruded(text: str) -> tuple[float, float | None]:
    """Wie viel Filament durch die Düse ging — insgesamt und für Stützen (§28.1).

    Gemessen, nicht geschätzt: die E-Achse sagt, wie viel Material in eine Bahn
    ging, und die Typkommentare sagen, wofür. Ein Slicer, der den Typ nicht
    schreibt, lässt den Stützanteil unbekannt — und das ist besser als eine
    Zahl, die niemand prüfen kann. Die Gesamtlänge steht davon unabhängig, denn
    sie braucht keinen Typ.

    Ein Durchlauf für beide Zahlen: es ist dasselbe Band, dieselbe Achse und
    dieselbe Buchführung über absolut und relativ.
    """
    active = False
    seen_type = False
    total = 0.0
    support = 0.0
    previous = 0.0
    absolute = ";" not in text or "M83" not in text

    for line in text.splitlines():
        stripped = line.strip()
        kind = _SUPPORT_TOOL.match(stripped)
        if kind is not None:
            seen_type = True
            active = "support" in kind.group("type").casefold()
            continue
        if stripped.upper().startswith("M83"):
            absolute = False
            continue
        if stripped.upper().startswith("M82"):
            absolute = True
            continue
        if stripped.upper().startswith("G92") and " E" in stripped.upper():
            # Auf den genannten Wert, nicht auf null: ``G92 E0`` ist zwar der
            # Regelfall, aber die Gesamtsumme hängt an jedem Rücksetzpunkt —
            # ein angenommener wäre ein Fehler, der sich über die ganze Datei
            # fortschreibt.
            previous = _reset_value(stripped)
            continue

        found = _EXTRUSION.match(stripped)
        if found is None:
            continue
        value = float(found.group("e"))
        step = value - previous if absolute else value
        if absolute:
            previous = value
        # Für die Gesamtmenge zählt auch ein Rückschritt: was zurückgezogen
        # wurde, ist nicht gefördert. Für die Stützen bleibt es beim positiven
        # Anteil — ein Rückzug gehört keinem Abschnitt.
        total += step
        if active and step > 0.0:
            support += step

    return max(total, 0.0), support if seen_type else None


def _reset_value(line: str) -> float:
    found = re.search(r"\bE(-?[0-9.]+)", line, re.IGNORECASE)
    return 0.0 if found is None else float(found.group(1))


@dataclass(slots=True)
class CrossCheck:
    """Die interne Schätzung gegen den gemessenen Wert (§28.2)."""

    what: str
    estimated: float
    measured: float
    findings: list[Finding] = field(default_factory=list)

    @property
    def deviation(self) -> float:
        """Relativer Unterschied. Positiv heißt: die Schätzung lag zu niedrig."""
        if self.measured <= 0.0:
            return 0.0
        return (self.measured - self.estimated) / self.measured

    @property
    def within_limit(self) -> bool:
        return abs(self.deviation) <= DEVIATION_LIMIT


def compare(estimated: float, measured: float, what: str = "support") -> CrossCheck:
    """Prüft eine Größe gegen. Ein großer Unterschied ist ein Befund, keine
    Korrektur.

    §28.2: die interne Schätzung wird nicht still durch den gemessenen Wert
    ersetzt. Beide bleiben, beide behalten ihre Herkunft, und der Bericht sagt,
    dass sie sich widersprechen — das ist das Signal, dass die Schichtanalyse
    Arbeit braucht.
    """
    check = CrossCheck(what=what, estimated=estimated, measured=measured)
    if measured <= 0.0:
        # Eine Null ist keine Messung, und `deviation` gäbe für sie glatt
        # null zurück — die größtmögliche Abweichung sähe aus wie die
        # perfekte Übereinstimmung. „Nicht vergleichbar" ist die ehrliche
        # Antwort, und sie trägt ihre Herkunft (Regel 14).
        check.findings.append(
            Finding(
                code="gcode.no_measurement",
                severity="info",
                message=_("Die Druckdatei nennt für diese Größe keinen Messwert."),
                values={"what": what, "estimated": round(estimated, 2)},
                source="gcode",
            )
        )
        return check
    if not check.within_limit:
        check.findings.append(
            Finding(
                code="gcode.deviation",
                severity="warning",
                message=_("Die Gegenprobe aus dem G-Code weicht deutlich von der Schätzung ab."),
                values={
                    "what": what,
                    "estimated": round(estimated, 2),
                    "measured": round(measured, 2),
                    "deviation": f"{check.deviation:+.0%}",
                },
                source="gcode",
            )
        )
    return check


def combine(parts: Sequence[GcodeMetrics]) -> GcodeMetrics:
    """Die Kennzahlen mehrerer Druckplatten als eine Auskunft.

    Ein Auftrag, der auf zwei Platten passt, wird zweimal gedruckt — Zeit und
    Material addieren sich also, und wer wissen will, was der Satz kostet, will
    diese Summe sehen. Alle Werte kommen aus derselben Quelle (G-Code), Regel 14
    ist damit gewahrt: hier wird nichts mit einer Schätzung vermischt.

    **Fehlt ein Wert bei einer Platte, fehlt die Summe.** Die Alternative wäre,
    ihn als null zu behandeln — und dann stünde eine Gesamtzeit da, die zu kurz
    ist, ohne dass jemand es sehen kann. Das ist derselbe Grundsatz, mit dem
    :class:`GcodeMetrics` seine Felder optional führt.

    Die Schichtzahl wird **nicht** summiert. Sie beschreibt eine Platte; über
    zwei addiert ergäbe sie eine Zahl, die es nirgends gibt. Sie steht deshalb
    nur da, wo es eine Platte ist.
    """
    if not parts:
        return GcodeMetrics()
    if len(parts) == 1:
        return parts[0]

    def total(pick: Callable[[GcodeMetrics], float | None]) -> float | None:
        values = [pick(entry) for entry in parts]
        return (
            None
            if any(value is None for value in values)
            else sum(value or 0.0 for value in values)
        )

    heights = {entry.layer_height for entry in parts if entry.layer_height is not None}
    warnings: list[str] = []
    for entry in parts:
        warnings += [text for text in entry.warnings if text not in warnings]

    return GcodeMetrics(
        slicer=parts[0].slicer,
        print_seconds=total(lambda entry: entry.print_seconds),
        filament_mm=total(lambda entry: entry.filament_mm),
        filament_grams=total(lambda entry: entry.filament_grams),
        support_mm3=total(lambda entry: entry.support_mm3),
        layer_count=None,
        layer_height=heights.pop() if len(heights) == 1 else None,
        warnings=tuple(warnings),
        source="gcode",
    )


def findings_for(metrics: GcodeMetrics) -> list[Finding]:
    """Was die geslicete Datei sagt, als Einträge für den Prüfbericht — als
    gemessen markiert.
    """
    findings: list[Finding] = []
    if metrics.print_minutes is not None:
        findings.append(
            Finding(
                code="gcode.print_time",
                severity="info",
                message=_("Druckzeit aus dem G-Code."),
                values={"minutes": round(metrics.print_minutes, 1)},
                source="gcode",
            )
        )
    grams = metrics.grams()
    if grams is not None:
        findings.append(
            Finding(
                code="gcode.material",
                severity="info",
                message=_("Materialverbrauch aus dem G-Code."),
                values={"grams": round(grams, 1)},
                source="gcode",
            )
        )
    for warning in metrics.warnings:
        findings.append(
            Finding(
                code="gcode.warning",
                severity="warning",
                message=_("Der Slicer hat gewarnt."),
                values={"text": warning},
                source="gcode",
            )
        )
    return findings
