"""Reading G-code back (Bauplan §28.1, §28.2).

The layer analysis (§22) searches and judges; the external slicer delivers the
truth for the file that goes to the printer. This module reads that truth back:
print time, material, **measured** support volume, layer count, warnings.

The relationship is the way round §28.2 describes it. The search runs internally
over hundreds of candidates; the external run confirms the winner and gives the
cost estimate. So this is not a second slicer, it is the final acceptance.

Every number that comes out of here carries ``source="gcode"`` and is never
mixed with an internal estimate (§22.5). Where the two differ by more than a
sixth, that is a finding — and a hint that the layer analysis needs work, not a
reason to quietly prefer one of them.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from app.core.log import get_logger
from app.core.types import Finding, MetricSource
from app.i18n import _

_log = get_logger(__name__)

#: Above this relative difference the cross-check becomes a finding (§28.2).
DEVIATION_LIMIT = 0.15

#: Density of the usual filaments in g/cm³ — for the weight from the length.
DEFAULT_DENSITY = 1.24

#: Cross section of a 1.75 mm filament in mm².
FILAMENT_AREA = 2.405


@dataclass(slots=True)
class GcodeMetrics:
    """What a sliced file says about itself.

    Everything optional: slicers write different comments, and a missing value
    is missing — it is not zero. That distinction is the whole point of reading
    the file rather than guessing from it.
    """

    slicer: str = ""
    print_seconds: float | None = None
    filament_mm: float | None = None
    filament_grams: float | None = None
    support_mm3: float | None = None
    layer_count: int | None = None
    layer_height: float | None = None
    warnings: tuple[str, ...] = ()
    source: MetricSource = "gcode"

    @property
    def print_minutes(self) -> float | None:
        return None if self.print_seconds is None else self.print_seconds / 60.0

    @property
    def material_cm3(self) -> float | None:
        """Filament length as volume — the figure comparable with the estimate."""
        if self.filament_mm is None:
            return None
        return self.filament_mm * FILAMENT_AREA / 1000.0

    def grams(self, density: float = DEFAULT_DENSITY) -> float | None:
        if self.filament_grams is not None:
            return self.filament_grams
        volume = self.material_cm3
        return None if volume is None else volume * density


#: Comment lines the common slicers write. One pattern per fact, not one parser
#: per slicer: a new slicer usually only needs another line here.
_PATTERNS: tuple[tuple[str, str], ...] = (
    ("print_seconds", r";\s*estimated printing time.*?=\s*(?P<value>[0-9hmsd ]+)"),
    ("print_seconds", r";\s*TIME:\s*(?P<value>[0-9.]+)"),
    ("print_seconds", r";\s*total print time.*?:\s*(?P<value>[0-9hmsd ]+)"),
    ("filament_mm", r";\s*filament used \[mm\]\s*=\s*(?P<value>[0-9.]+)"),
    ("filament_mm", r";\s*Filament used:\s*(?P<value>[0-9.]+)m\b"),
    ("filament_grams", r";\s*filament used \[g\]\s*=\s*(?P<value>[0-9.]+)"),
    ("layer_count", r";\s*(?:total )?layer count\s*[:=]\s*(?P<value>[0-9]+)"),
    ("layer_count", r";\s*LAYER_COUNT:\s*(?P<value>[0-9]+)"),
    ("layer_height", r";\s*layer_height\s*=\s*(?P<value>[0-9.]+)"),
    ("layer_height", r";\s*Layer height:\s*(?P<value>[0-9.]+)"),
    ("slicer", r";\s*(?:generated by|Generated with)\s*(?P<value>.+)"),
)

_SUPPORT_TOOL = re.compile(r";\s*TYPE:\s*(?P<type>.+)", re.IGNORECASE)
_EXTRUSION = re.compile(r"^G1\b(?=.*\bE(?P<e>-?[0-9.]+))(?=.*\b[XY])", re.IGNORECASE)
_WARNING = re.compile(r";\s*(?:WARNING|Warnung)[:\s]\s*(?P<text>.+)", re.IGNORECASE)


def parse(text: str) -> GcodeMetrics:
    """Read a G-code file. What is not in it stays unknown."""
    metrics = GcodeMetrics()
    warnings: list[str] = []

    for name, pattern in _PATTERNS:
        if getattr(metrics, name) is not None and getattr(metrics, name) != "":
            continue
        found = re.search(pattern, text, re.IGNORECASE)
        if found is None:
            continue
        _set(metrics, name, found.group("value").strip())

    for line in text.splitlines():
        found = _WARNING.match(line.strip())
        if found:
            warnings.append(found.group("text").strip())

    metrics.support_mm3 = _support_volume(text, metrics.layer_height or 0.2)
    metrics.warnings = tuple(warnings)
    _log.info("read g-code of %s", metrics.slicer or "unknown slicer")
    return metrics


def _set(metrics: GcodeMetrics, name: str, value: str) -> None:
    if name == "slicer":
        metrics.slicer = value
        return
    if name == "print_seconds":
        metrics.print_seconds = _seconds(value)
        return
    number = _number(value)
    if number is None:
        return
    if name == "filament_mm":
        # "Filament used: 3.42m" is metres, "filament used [mm] = 3420" is not.
        metrics.filament_mm = number * 1000.0 if number < 100.0 else number
    elif name == "filament_grams":
        metrics.filament_grams = number
    elif name == "layer_count":
        metrics.layer_count = int(number)
    elif name == "layer_height":
        metrics.layer_height = number


def _number(value: str) -> float | None:
    try:
        return float(value)
    except ValueError:
        return None


def _seconds(value: str) -> float | None:
    """``2h 14m 3s``, ``14m``, or plain seconds — all of them appear."""
    plain = _number(value)
    if plain is not None:
        return plain
    total = 0.0
    found = False
    for amount, unit in re.findall(r"(\d+)\s*([dhms])", value.lower()):
        found = True
        total += float(amount) * {"d": 86400.0, "h": 3600.0, "m": 60.0, "s": 1.0}[unit]
    return total if found else None


def _support_volume(text: str, layer_height: float) -> float | None:
    """Extruded filament while the tool was printing support (§28.1).

    Measured, not estimated: the file says which stretches are support, and the
    E axis says how much material went into them. Slicers that do not write the
    type leave this unknown, which is better than a number nobody can check.
    """
    active = False
    seen_type = False
    extruded = 0.0
    previous: float | None = None
    absolute = ";" not in text or "M83" not in text

    for line in text.splitlines():
        stripped = line.strip()
        kind = _SUPPORT_TOOL.match(stripped)
        if kind is not None:
            seen_type = True
            active = "support" in kind.group("type").casefold()
            continue
        if stripped.upper().startswith("M83"):
            absolute = False
            continue
        if stripped.upper().startswith("M82"):
            absolute = True
            continue
        if stripped.upper().startswith("G92") and " E" in stripped.upper():
            previous = 0.0
            continue

        found = _EXTRUSION.match(stripped)
        if found is None:
            continue
        value = float(found.group("e"))
        step = value - (previous or 0.0) if absolute else value
        if absolute:
            previous = value
        if active and step > 0.0:
            extruded += step

    if not seen_type:
        return None
    return extruded * FILAMENT_AREA


@dataclass(slots=True)
class CrossCheck:
    """The internal estimate against the measured value (§28.2)."""

    what: str
    estimated: float
    measured: float
    findings: list[Finding] = field(default_factory=list)

    @property
    def deviation(self) -> float:
        """Relative difference. Positive means the estimate was too low."""
        if self.measured <= 0.0:
            return 0.0
        return (self.measured - self.estimated) / self.measured

    @property
    def within_limit(self) -> bool:
        return abs(self.deviation) <= DEVIATION_LIMIT


def compare(estimated: float, measured: float, what: str = "support") -> CrossCheck:
    """Cross-check one figure. A large difference is a finding, not a correction.

    §28.2: the internal estimate is not quietly replaced by the measured value.
    Both stay, both keep their origin, and the report says they disagree — that
    is the signal that the layer analysis needs work.
    """
    check = CrossCheck(what=what, estimated=estimated, measured=measured)
    if not check.within_limit:
        check.findings.append(
            Finding(
                code="gcode.deviation",
                severity="warning",
                message=_("Die Gegenprobe aus dem G-Code weicht deutlich von der Schätzung ab."),
                values={
                    "what": what,
                    "estimated": round(estimated, 2),
                    "measured": round(measured, 2),
                    "deviation": f"{check.deviation:+.0%}",
                },
                source="gcode",
            )
        )
    return check


def findings_for(metrics: GcodeMetrics) -> list[Finding]:
    """What the sliced file says, as entries for the report — marked as measured."""
    findings: list[Finding] = []
    if metrics.print_minutes is not None:
        findings.append(
            Finding(
                code="gcode.print_time",
                severity="info",
                message=_("Druckzeit aus dem G-Code."),
                values={"minutes": round(metrics.print_minutes, 1)},
                source="gcode",
            )
        )
    grams = metrics.grams()
    if grams is not None:
        findings.append(
            Finding(
                code="gcode.material",
                severity="info",
                message=_("Materialverbrauch aus dem G-Code."),
                values={"grams": round(grams, 1)},
                source="gcode",
            )
        )
    for warning in metrics.warnings:
        findings.append(
            Finding(
                code="gcode.warning",
                severity="warning",
                message=_("Der Slicer hat gewarnt."),
                values={"text": warning},
                source="gcode",
            )
        )
    return findings
