"""G-Code zurücklesen und gegenprüfen (Bauplan §28.1, §28.2, §22.5)."""

from __future__ import annotations

import pytest

from app.core.slice import gcode

PRUSA = """
; generated by PrusaSlicer 2.8.0 on 2026-07-28
; layer_height = 0.2
M83
;TYPE:Perimeter
G1 X10 Y10 E0.5
G1 X20 Y10 E0.5
;TYPE:Support material
G1 X30 Y10 E2.0
G1 X40 Y10 E2.0
;TYPE:Perimeter
G1 X50 Y10 E0.5
; filament used [mm] = 3420.5
; filament used [g] = 10.2
; total layer count = 145
; estimated printing time (normal mode) = 2h 14m 3s
"""

CURA = """
;Generated with Cura_SteamEngine 5.7.0
;LAYER_COUNT:88
;Layer height: 0.15
;TIME:4530
;Filament used: 3.42m
M82
;TYPE:WALL-OUTER
G1 X10 Y10 E1.0
;TYPE:SUPPORT
G1 X20 Y10 E3.0
G1 X30 Y10 E5.0
"""


# --- reading (§28.1) ----------------------------------------------------------------


def test_a_prusa_file_gives_up_its_numbers() -> None:
    metrics = gcode.parse(PRUSA)

    assert "PrusaSlicer" in metrics.slicer
    assert metrics.print_seconds == pytest.approx(2 * 3600 + 14 * 60 + 3)
    assert metrics.filament_mm == pytest.approx(3420.5)
    assert metrics.filament_grams == pytest.approx(10.2)
    assert metrics.layer_count == 145
    assert metrics.layer_height == pytest.approx(0.2)


def test_a_cura_file_gives_up_its_numbers() -> None:
    """Andere Kommentare, dieselben Tatsachen — ein Muster je Tatsache, nicht
    eines je Slicer.
    """
    metrics = gcode.parse(CURA)

    assert "Cura" in metrics.slicer
    assert metrics.print_seconds == pytest.approx(4530.0)
    assert metrics.layer_count == 88
    assert metrics.filament_mm == pytest.approx(3420.0), "metres become millimetres"


def test_the_layer_count_is_counted_where_it_is_not_written() -> None:
    """PrusaSlicer nennt die Schichtzahl nicht immer — er markiert die Wechsel.

    Der Kopf einer echten Datei aus 2.9.6 trägt keine Gesamtzahl; im
    Prüfbericht stand deshalb bei jedem Prusa-Lauf nichts, wo bei Cura eine
    Zahl steht. Gezählte Marken sind dieselbe Auskunft.
    """
    without_header = """
; generated by PrusaSlicer 2.9.6 on 2026-08-20
;LAYER_CHANGE
G1 X10 Y10 E0.5
;LAYER_CHANGE
G1 X20 Y10 E0.5
;LAYER_CHANGE
G1 X30 Y10 E0.5
"""

    assert gcode.parse(without_header).layer_count == 3
    # Steht sie doch im Kopf, gilt die Aussage des Slicers — sie kennt auch
    # Schichten, die keine Bahn zeigen.
    assert gcode.parse(PRUSA).layer_count == 145


def test_what_is_not_in_the_file_stays_unknown() -> None:
    """Ein fehlender Wert fehlt, er ist nicht null — genau darum wird die
    Datei gelesen.

    Die Materiallänge steht hier trotzdem: eine Bahn mit Vorschub *ist* eine
    Aussage der Datei über das Filament, das durch sie ging. Zeit und
    Schichtzahl sagt nur der Kopf, und der schweigt.
    """
    metrics = gcode.parse("G1 X10 Y10 E1.0\n")

    assert metrics.print_seconds is None
    assert metrics.filament_mm == pytest.approx(1.0), "die Bahn sagt es, auch ohne Kopf"
    assert metrics.layer_count is None
    assert metrics.support_mm3 is None, "no type comments, no measured support"


def test_a_file_without_any_move_says_nothing_about_material() -> None:
    """Ohne Bahn und ohne Kopf bleibt die Länge unbekannt — nicht null."""
    metrics = gcode.parse(";FLAVOR:Marlin\nG28\nM104 S200\n")

    assert metrics.filament_mm is None


def test_curas_empty_header_does_not_become_a_measurement() -> None:
    """`CuraEngine` schreibt den Kopf, bevor es rechnet.

    Im Fenster füllt Cura „Filament used" nachträglich aus; von der
    Kommandozeile aus bleibt dort die Vorlage stehen. Gemessen an einem echten
    Lauf (5.13.0, 20-mm-Würfel): 1,8 MB Bahnen mit Vorschub, und im Kopf
    `Filament used: 0m`. Solidon meldete daraufhin null Meter und rechnete
    Kosten von null — die Datei selbst weiß es besser.
    """
    metrics = gcode.parse(
        ";Filament used: 0m\n;LAYER_COUNT:2\nM82\nG1 X10 Y10 E2.0\nG1 X20 Y10 E5.5\n"
    )

    assert metrics.filament_mm == pytest.approx(5.5)
    assert metrics.layer_count == 2, "was der Kopf sagt, gilt weiter"


def test_the_last_layer_mark_beats_the_header_time() -> None:
    """`;TIME:6666` ist Curas Vorlage, keine Zeit.

    Sie sieht mit 111 Minuten plausibel aus und steht für jedes Modell gleich
    da — auch für einen halb so hohen Würfel. Am Ende der Datei steht die
    gerechnete Zeit: gemessen 20,8 Minuten für einen 20-mm-Würfel, gegen 21 bei
    PrusaSlicer mit denselben Einstellungen.
    """
    metrics = gcode.parse(
        ";TIME:6666\n;LAYER:0\n;TIME_ELAPSED:45.96\n;LAYER:1\n;TIME_ELAPSED:1249.49\n"
    )

    assert metrics.print_seconds == pytest.approx(1249.49)


def test_a_stated_length_beats_the_moves() -> None:
    """Der Kopf kennt, was keine Bahn zeigt: Vorschieben, Reinigungsturm,
    Werkzeugwechsel. Wo er etwas sagt, gilt er."""
    metrics = gcode.parse(";filament used [mm] = 4000\nM82\nG1 X10 Y10 E2.0\n")

    assert metrics.filament_mm == pytest.approx(4000.0)


def test_the_support_volume_is_measured_not_guessed() -> None:
    """§28.1: gemessenes Stützmaterial — aus den Typ-Kommentaren und der
    E-Achse.
    """
    metrics = gcode.parse(PRUSA)

    assert metrics.support_mm3 is not None
    assert metrics.support_mm3 == pytest.approx(4.0 * gcode.FILAMENT_AREA, rel=1e-6)


def test_absolute_extrusion_is_counted_as_differences() -> None:
    metrics = gcode.parse(CURA)

    assert metrics.support_mm3 is not None
    # E läuft 1 → 3 → 5, mit dem Werkzeug auf Stützen für die letzten zwei Wege.
    assert metrics.support_mm3 == pytest.approx(4.0 * gcode.FILAMENT_AREA, rel=1e-6)


def test_the_weight_follows_from_the_length() -> None:
    metrics = gcode.parse(CURA)

    assert metrics.material_cm3 == pytest.approx(3420.0 * gcode.FILAMENT_AREA / 1000.0)
    assert metrics.grams() == pytest.approx(metrics.material_cm3 * gcode.DEFAULT_DENSITY)


def test_a_stated_weight_wins_over_the_computed_one() -> None:
    assert gcode.parse(PRUSA).grams() == pytest.approx(10.2)


def test_a_slicer_warning_travels_along() -> None:
    metrics = gcode.parse("; WARNING: Detected print stability issues\nG1 X1 E1\n")

    assert metrics.warnings == ("Detected print stability issues",)


# --- der Abgleich (§28.2) ------------------------------------------------------------


def test_a_close_estimate_says_nothing() -> None:
    check = gcode.compare(estimated=1000.0, measured=1050.0)

    assert check.within_limit
    assert check.findings == []


def test_a_far_estimate_becomes_a_finding() -> None:
    """§28.2: ein klarer Unterschied ist ein Befund — und ein Hinweis, §22 zu
    verbessern.
    """
    check = gcode.compare(estimated=500.0, measured=1000.0, what="support")

    assert not check.within_limit
    assert check.deviation == pytest.approx(0.5)
    assert check.findings[0].code == "gcode.deviation"
    assert check.findings[0].severity == "warning"
    assert "+50%" in str(check.findings[0].values["deviation"])


def test_the_estimate_is_never_replaced_by_the_measurement() -> None:
    """§22.5: beide bleiben, beide behalten ihre Herkunft. Nichts wird still überschrieben."""
    check = gcode.compare(estimated=500.0, measured=1000.0)

    assert check.estimated == 500.0
    assert check.measured == 1000.0
    assert check.findings[0].source == "gcode"


def test_every_measured_finding_says_it_was_measured() -> None:
    """§22.5: eine Schätzung und eine Messung sehen nie gleich aus."""
    metrics = gcode.parse(PRUSA)
    findings = gcode.findings_for(metrics)

    assert findings
    assert all(finding.source == "gcode" for finding in findings)
    codes = {finding.code for finding in findings}
    assert {"gcode.print_time", "gcode.material"} <= codes


def test_an_internal_finding_stays_internal() -> None:
    """Die andere Hälfte derselben Regel, von der anderen Seite geprüft."""
    import trimesh

    from app.core.geom.mesh import MeshData
    from app.core.slice.analysis import slice_body

    body = MeshData.of(trimesh.creation.box(extents=(20.0, 20.0, 10.0)))
    result = slice_body(body, 0.2)

    assert result.source == "internal"


def test_a_file_without_a_single_extrusion_is_not_a_print() -> None:
    """Cura schreibt bei fehlender Einstellung eine große Datei voller
    Leerfahrten und meldet trotzdem Erfolg. Gefragt wird an der Bewegung,
    nicht am Kommentar — sonst hinge die Antwort am Slicer.
    """
    leerlauf = """
;FLAVOR:Marlin
;TIME:6666
;Filament used: 0m
G0 X10 Y10
G1 X20 Y10 E0
G0 X30 Y10
"""
    assert not gcode.extrudes(leerlauf)
    assert gcode.extrudes(PRUSA)


# --- mehrere Platten (§25, §29) -----------------------------------------------


def test_two_plates_add_up_to_one_job() -> None:
    """Zeit und Material addieren sich, weil zweimal gedruckt wird."""
    first = gcode.GcodeMetrics(print_seconds=600.0, filament_mm=1000.0, filament_grams=10.0)
    second = gcode.GcodeMetrics(print_seconds=1200.0, filament_mm=2000.0, filament_grams=20.0)

    total = gcode.combine([first, second])

    assert total.print_seconds == 1800.0
    assert total.filament_mm == 3000.0
    assert total.filament_grams == 30.0
    assert total.source == "gcode"


def test_a_missing_value_on_one_plate_leaves_the_sum_missing() -> None:
    """Sonst stünde eine Gesamtzeit da, die zu kurz ist — und niemand sähe es.

    Dieselbe Unterscheidung, aus der ``GcodeMetrics`` seine Felder optional
    führt: ein fehlender Wert fehlt, er ist nicht null.
    """
    first = gcode.GcodeMetrics(print_seconds=600.0, filament_grams=10.0)
    second = gcode.GcodeMetrics(filament_grams=20.0)

    total = gcode.combine([first, second])

    assert total.print_seconds is None
    assert total.filament_grams == 30.0


def test_the_layer_count_belongs_to_a_plate_and_not_to_a_job() -> None:
    """Über zwei Platten addiert wäre sie eine Zahl, die es nirgends gibt."""
    plates = [gcode.GcodeMetrics(layer_count=110), gcode.GcodeMetrics(layer_count=40)]

    assert gcode.combine(plates).layer_count is None
    # Bei einer Platte bleibt sie, denn dort sagt sie etwas.
    assert gcode.combine(plates[:1]).layer_count == 110


def test_one_plate_comes_back_unchanged() -> None:
    """Der einfarbige Einzelauftrag ist der Sonderfall mit einem Eintrag,
    nicht ein anderer Weg."""
    only = gcode.parse(PRUSA)

    assert gcode.combine([only]) is only
    assert gcode.combine([]) == gcode.GcodeMetrics()


def test_a_zero_measurement_is_not_a_perfect_match() -> None:
    """`deviation` gab für `measured=0` glatt null zurück — die größtmögliche
    Abweichung sah aus wie die perfekte Übereinstimmung. Eine Null ist keine
    Messung, sondern „nicht vergleichbar" (Regel 14)."""
    check = gcode.compare(12.0, 0.0, "material")

    assert [entry.code for entry in check.findings] == ["gcode.no_measurement"]
    assert all(entry.code != "gcode.deviation" for entry in check.findings)


def test_a_zero_gram_header_falls_back_to_the_length() -> None:
    """`filament_grams` hat dieselbe Null-Absicherung wie `filament_mm` seit
    dem Cura-Vorfall: dessen Kopf schreibt die Werte, bevor gerechnet wird."""
    metrics = gcode.GcodeMetrics(filament_mm=1000.0, filament_grams=0.0)

    grams = metrics.grams(density=1.24)

    assert grams is not None and grams > 0.0, "die Länge trägt, nicht die leere Kopfzeile"


# --- wohin die Datei wirklich druckt (§29) -------------------------------------

#: Ein Anfang, wie der ElegooSlicer ihn schreibt: die Reinigung steht **vor**
#: der ersten Schicht und 1,2 mm vor dem Bett, das dieselbe Datei nennt.
ELEGOO_START = """
; printable_area = 0x0,256x0,256x256,0x256
; printable_height = 256
G90
M83
G1 X127 Y-1.2 F20000
G1 Z0.5 F900
G92 E0 ;Reset Extruder
G1 E6 F120
G1 X87 E20 F1200
;LAYER_COUNT:2
;LAYER:0
G1 Z0.2
G1 X120 Y120 E0.5
G1 X136 Y136 E0.5
"""


def test_the_start_code_of_the_machine_is_not_the_print() -> None:
    """Zwei Gründe, aus denen dieselbe Datei sonst 1,2 mm neben der Platte
    druckt — und beide sind gemessen, nicht gedacht.

    ``G1 E6 F120`` fördert sechs Millimeter, ohne einen zu fahren: das ist die
    Reinigung, keine Bahn. Und ``G1 X87 E20`` **fährt** dabei, liegt aber vor
    der ersten Schicht — es ist der Startcode des Maschinenprofils, den die
    Orca-Familie aus ihrem eigenen Bestand mitbringt und den Solidon nicht
    beurteilt (§29).

    Übrig bleibt das Modell: zwei Bahnen um die Bettmitte.
    """
    box = gcode.printed_extent(ELEGOO_START)

    assert box is not None
    assert box.minimum[:2] == (120.0, 120.0), "die Reinigungsbahn zählt nicht mit"
    assert box.maximum[:2] == (136.0, 136.0)


def test_without_a_layer_mark_everything_counts() -> None:
    """Die Gegenprobe: Wo keine Schichtmarke steht, gibt es auch keinen
    Startcode zum Abtrennen — dann wird die ganze Datei gemessen."""
    ohne_marke = "\n".join(
        line for line in ELEGOO_START.splitlines() if not line.startswith(";LAYER")
    )

    box = gcode.printed_extent(ohne_marke)

    assert box is not None
    assert box.minimum[1] == pytest.approx(-1.2), "jetzt zählt die Reinigungsbahn mit"


def test_a_purge_without_movement_is_never_a_path() -> None:
    """Und die zweite Hälfte einzeln: eine Förderung ohne Fahrweg ist keine
    Bahn, gleich wo sie steht (dieselbe Bedingung wie in ``extrudes``)."""
    stehend = "G90\nG1 X50 Y-9 F9000\nG1 E12 F120\n"

    assert gcode.printed_extent(stehend) is None


def test_the_file_says_which_bed_it_printed_on() -> None:
    """Die einzige Auskunft, die vom Slicer selbst kommt.

    Gemessen an den drei Familien: die Orca-Familie schreibt
    ``printable_area`` und ``printable_height``, PrusaSlicer ``bed_shape``
    und ``max_print_height``, CuraEngine keines von beiden. Gegen Solidons
    eigenen Bauraum zu messen hieße bei den ersten zwei, eine Abweichung
    zwischen zwei Maschinenprofilen als Druckfehler zu melden.
    """
    orca = gcode.stated_bed(ELEGOO_START)
    prusa = gcode.stated_bed(
        "; bed_shape = -110x-110,110x-110,110x110,-110x110\n; max_print_height = 250\n"
    )

    assert orca is not None
    assert (orca.minimum, orca.maximum) == ((0.0, 0.0, 0.0), (256.0, 256.0, 256.0))
    assert prusa is not None
    assert (prusa.minimum, prusa.maximum) == ((-110.0, -110.0, 0.0), (110.0, 110.0, 250.0))
    assert gcode.stated_bed(CURA) is None, "CuraEngine schreibt seine Bettform nicht"
