"""G-Code zurücklesen und gegenprüfen (Bauplan §28.1, §28.2, §22.5)."""

from __future__ import annotations

import math

import pytest

from app.core.slice import gcode


@pytest.mark.parametrize("move", ["G1 X10 Y10E2", "G1X10Y10E2", "g01x10y10e2"])
def test_compact_words_keep_extrusion_separate_from_coordinates(move: str) -> None:
    """E ist auch ohne Leerzeichen eine Extrusion und kein Zehnerexponent."""
    result = gcode.analyze(f"G90\nM83\nG0 X0 Y0 Z0.2\n{move}\n")

    assert result.extrudes
    assert result.metrics.filament_mm == pytest.approx(2.0)
    assert result.extent is not None
    assert result.extent.maximum == pytest.approx((10.0, 10.0, 0.2))


def test_cura_placeholder_is_replaced_for_the_active_tool_only() -> None:
    metrics = gcode.parse(
        ";Generated with Cura_SteamEngine 5.13.0\n;Filament used: 0m, 0m, 0m\n"
        "M83\nT2\nG0 X0 Y0\nG1 X10 E174.31766\n",
        diameters=(1.75, 1.75, 1.75),
        densities=(1.24, 1.24, 1.24),
    )
    assert metrics.filament_mm_by_tool == pytest.approx((0, 0, 174.31766))
    assert metrics.grams_by_tool() == pytest.approx(
        (0, 0, 174.31766 * math.pi * 1.75**2 / 4000 * 1.24)
    )
    assert metrics.filament_mm_sources == ("header", "header", "motion")
    assert metrics.used_tools == (2,)


def test_material_and_support_use_each_tools_actual_diameter_and_density() -> None:
    metrics = gcode.parse(
        "; filament_diameter = 1.75,2.85\n; filament_density = 1.24,1.05\n"
        "; filament used [mm] = 1000,1000\nM83\nG0 X0 Y0\n"
        ";TYPE:Support material\nT0\nG1 X10 E100\nT1\nG1 X20 E100\n",
        diameters=(1.0, 1.0),
        densities=(1.0, 1.0),
    )
    assert metrics.material_cm3 == pytest.approx(8.7846784576)
    assert metrics.support_mm3 == pytest.approx(878.46784576)
    assert metrics.grams_by_tool() == pytest.approx((2.98254952596, 6.69836641131))
    assert metrics.grams() == pytest.approx(9.68091593727)


def test_missing_material_is_unknown_but_explicit_caller_properties_work() -> None:
    text = "; filament used [mm] = 1000\nM83\n;TYPE:Support\nG1 X10 E100\n"
    missing = gcode.parse(text)
    assert missing.material_cm3 is None
    assert missing.grams() is None
    assert missing.support_mm3 is None
    explicit = gcode.parse(text, diameters=(2.85,), densities=(1.24,))
    assert explicit.material_cm3 == pytest.approx(6.3793965822)
    assert explicit.grams() == pytest.approx(7.91045176192)
    assert explicit.support_mm3 == pytest.approx(637.93965822)


def test_bambu_282_header_and_layer_marker_exclude_machine_purge() -> None:
    result = gcode.analyze(
        "; HEADER_BLOCK_START\n; BambuStudio 02.08.02.61\n"
        "; model printing time: 5m 59s; total estimated time: 6m 18s\n"
        "; total layer number: 20\n; total filament length [mm] : 461.57\n"
        "; total filament volume [cm^3] : 1110.21\n"
        "; total filament weight [g] : 1.38\n"
        "; filament_density: 1.24,1.24\n; filament_diameter: 1.75,1.75\n"
        "; HEADER_BLOCK_END\nG90\nM83\nG0 X0 Y-2 Z0.2\nG1 X50 E50\n"
        "; CHANGE_LAYER\n; layer num/total_layer_count: 1/20\n"
        "G0 X10 Y10\nG1 X20 E5\n"
    )
    metrics = result.metrics
    assert metrics.slicer == "BambuStudio 02.08.02.61"
    assert metrics.print_seconds == pytest.approx(378)
    assert metrics.layer_count == 20
    assert metrics.filament_mm == pytest.approx(461.57)
    assert metrics.grams() == pytest.approx(1.38)
    assert metrics.material_cm3 == pytest.approx(461.57 * math.pi * 1.75**2 / 4000)
    assert result.extent is not None
    assert result.extent.minimum[:2] == pytest.approx((10, 10))


@pytest.mark.parametrize("special", [255, 1000, 1100])
def test_bambu_special_commands_keep_the_current_filament(special: int) -> None:
    """Der reale A1-Startcode wechselt mit T1000 kein physisches Filament."""
    metrics = gcode.parse(
        f"; BambuStudio 02.08.02.61\nM83\n    T1\nG0 X0 Y0\nG1 X10 E2\nT{special}\nG1 X20 E3\n"
    )
    assert metrics.used_tools == (1,)
    assert metrics.filament_mm_by_tool == pytest.approx((0, 5))


def test_orca_bambu_machine_commands_identify_special_tools_without_a_bambu_header() -> None:
    metrics = gcode.parse(
        "; generated by OrcaSlicer\nM620 S1A\nT1\nM621 S1A\nM83\nG0 X0 Y0\nT1000\nG1 X10 E2\n"
    )
    assert metrics.used_tools == (1,)
    assert metrics.filament_mm_by_tool == pytest.approx((0, 2))


def test_a_bambu_single_used_filament_keeps_its_header_tool_number() -> None:
    metrics = gcode.parse(
        "; BambuStudio 02.08.02.61\n; total filament length [mm] : 237.51\n"
        "; total filament weight [g] : 0.71\n; filament: 2\n"
        "; filament_density: 1.24,1.24\n; filament_diameter: 1.75,1.75\n"
        "M83\nG1 E10\n    T1\nG0 X0 Y0\nT1000\nG1 X10 E2\n"
    )
    assert metrics.used_tools == (1,)
    assert metrics.filament_mm_by_tool == pytest.approx((0, 237.51))
    assert metrics.grams_by_tool() == pytest.approx((0, 0.71))
    assert metrics.grams() == pytest.approx(0.71)


def test_bambu_compacted_header_amounts_follow_the_declared_order() -> None:
    metrics = gcode.parse(
        "; BambuStudio 02.08.02.61\n; total filament length [mm] : 300,100\n"
        "; total filament weight [g] : 0.9,0.3\n; filament: 3,1\n"
    )
    assert metrics.filament_mm_by_tool == pytest.approx((100, 0, 300))
    assert metrics.filament_grams_by_tool == pytest.approx((0.3, 0, 0.9))


def test_unknown_firmware_does_not_inherit_bambu_special_tools() -> None:
    metrics = gcode.parse("M83\nT255\nG0 X0 Y0\nG1 X10 E2\n")
    assert metrics.used_tools == (255,)


@pytest.mark.parametrize("command", ["T1000000000", "M200 T1000000000 D1.75", "T" + "9" * 5000])
def test_tool_numbers_cannot_allocate_an_unbounded_result(command: str) -> None:
    from app.core.errors import ValidationError

    with pytest.raises(ValidationError):
        gcode.parse(f"M83\n{command}\nG0 X0 Y0\nG1 X10 E2\n")


@pytest.mark.parametrize("identifiers", ["1,1", "2,", "0", "1000000000", "9" * 5000])
def test_invalid_bambu_header_tools_have_an_actionable_error(identifiers: str) -> None:
    from app.core.errors import ValidationError

    with pytest.raises(ValidationError) as caught:
        gcode.parse(f"; BambuStudio 02.08.02.61\n; filament: {identifiers}\n")
    assert caught.value.suggestions


@pytest.mark.parametrize("dialect", [";FLAVOR:Marlin\n", "; gcode_flavor = marlin2\n"])
def test_marlin_g90_clears_relative_extrusion(dialect: str) -> None:
    result = gcode.analyze(dialect + "M83\nG90\nG0 X10 Y10 Z0.2\nG1 X20 E10\nG1 X300 E9\n")
    assert result.metrics.filament_mm == pytest.approx(9)
    assert result.extent is not None
    assert result.extent.maximum[0] == pytest.approx(20)


def test_marlin_g91_clears_absolute_extrusion() -> None:
    result = gcode.analyze(
        "M82\nG0 X10 Y10 Z0.2\nG91\nG1 X10 E1\nG1 X10 E2\n",
        firmware="marlin",
    )
    assert result.metrics.filament_mm == pytest.approx(3)


@pytest.mark.parametrize("dialect", ["", "; gcode_flavor = reprapfirmware\n"])
def test_marlin_extrusion_rules_are_not_assumed_for_unknown_firmware(dialect: str) -> None:
    metrics = gcode.parse(dialect + "M83\nG90\nG1 X10 E1\nG1 X20 E2\n")
    assert metrics.filament_mm == pytest.approx(3)


def test_footer_firmware_is_used_without_reading_the_stream_twice() -> None:
    lines = iter("M83\nG90\nG1 X10 E10\nG1 X300 E9\n; gcode_flavor = marlin\n".splitlines())
    result = gcode.analyze_lines(lines)
    assert result.metrics.filament_mm == pytest.approx(9)
    assert result.extent is not None
    assert result.extent.maximum[0] == pytest.approx(10)


def test_an_explicit_total_maps_to_the_only_observed_tool_without_losing_purge() -> None:
    metrics = gcode.parse(
        "; total filament length [mm] : 461.57\n; total filament weight [g] : 1.38\n"
        "M83\nT2\nG1 X20 E400\n"
    )
    assert metrics.filament_mm_by_tool == pytest.approx((0, 0, 461.57))
    assert metrics.grams_by_tool() == pytest.approx((0, 0, 1.38))
    assert metrics.filament_mm_sources == ("header", "header", "header")


def test_a_multi_tool_total_is_not_distributed_using_motion_ratios() -> None:
    metrics = gcode.parse(
        "; total filament length [mm] : 500\n; total filament weight [g] : 1.38\n"
        "M83\nT0\nG1 X20 E200\nT1\nG1 X30 E100\n"
    )
    assert metrics.filament_mm == pytest.approx(500)
    assert metrics.filament_mm_by_tool == pytest.approx((200, 100))
    assert metrics.filament_grams_by_tool == ()
    assert metrics.filament_mm_sources == ("motion", "motion")


def test_stationary_purge_of_another_tool_prevents_single_tool_total_assignment() -> None:
    metrics = gcode.parse("; total filament used [g] = 5\nM83\nT0\nG1 X10 E100\nT1\nG1 E100\n")
    assert metrics.used_tools == (0, 1)
    assert metrics.filament_grams_by_tool == ()
    assert metrics.grams() == pytest.approx(5)


def test_partial_material_data_does_not_hide_missing_tool_properties() -> None:
    metrics = gcode.parse("; filament used [mm] = 100,200\n; filament_diameter = 1.75\n")
    assert metrics.material_cm3 is None
    assert metrics.grams() is None


def test_combined_volume_keeps_each_plates_filament_diameter() -> None:
    first = gcode.parse("; filament used [mm] = 1000\n", diameters=(1.75,), densities=(1.24,))
    second = gcode.parse("; filament used [mm] = 1000\n", diameters=(2.85,), densities=(1.05,))
    combined = gcode.combine([first, second])
    assert combined.material_cm3 == pytest.approx(8.7846784576)
    assert combined.grams() == pytest.approx(9.68091593727)


def test_native_bed_polygons_keep_their_actual_vertices() -> None:
    result = gcode.analyze(
        "; printable_area = -100x0,0x-100,100x0,0x100\n"
        "; bed_exclude_area = 10x10,20x10,20x20,10x20\n"
    )
    assert result.bed_outline == ((-100, 0), (0, -100), (100, 0), (0, 100))
    assert result.excluded_areas == (((10, 10), (20, 10), (20, 20), (10, 20)),)


def test_stationary_extrusion_with_repeated_coordinates_is_not_a_print() -> None:
    result = gcode.analyze("M83\nG0 X10 Y10 Z0.2\nG1 X10 Y10 E5\n")
    assert not result.extrudes
    assert result.extent is None


def test_m200_extrusion_is_volume_and_not_linear_filament_length() -> None:
    metrics = gcode.parse(
        "M200 D1.75\nM83\n;TYPE:Support\nG0 X10 Y10\nG1 X20 E100\n",
        densities=(1.24,),
    )
    assert metrics.support_mm3 == pytest.approx(100)
    assert metrics.material_cm3 == pytest.approx(0.1)
    assert metrics.filament_mm == pytest.approx(100 / (math.pi * 1.75**2 / 4))
    assert metrics.grams() == pytest.approx(0.124)


@pytest.mark.parametrize("disable", ["M200 D0", "M200 S0", "M200 D0 S1"])
def test_m200_can_return_to_linear_extrusion_without_resetting_the_tool(disable: str) -> None:
    metrics = gcode.parse(
        "M83\nM200 D2\n;TYPE:Support\nG0 X0 Y0\nG1 X10 E100\n" + disable + "\nG1 X20 E10\n",
        densities=(1.24,),
    )
    assert metrics.filament_mm == pytest.approx(100 / math.pi + 10)
    assert metrics.material_cm3 == pytest.approx((100 + 10 * math.pi) / 1000)
    assert metrics.support_mm3 == pytest.approx(100 + 10 * math.pi)


def test_volumetric_tool_diameters_do_not_leak_into_each_other() -> None:
    metrics = gcode.parse(
        "M200 T0 D1.75\nM200 T2 D2.85\nM83\n;TYPE:Support\n"
        "G0 X0 Y0\nT0\nG1 X10 E100\nT2\nG1 X20 E100\n",
        densities=(1.24, None, 1.05),
    )
    assert metrics.filament_mm_by_tool == pytest.approx(
        (400 / (math.pi * 1.75**2), 0, 400 / (math.pi * 2.85**2))
    )
    assert metrics.grams_by_tool() == pytest.approx((0.124, 0, 0.105))
    assert metrics.support_mm3 == pytest.approx(200)


def test_volumetric_without_diameter_keeps_known_volume_and_unknown_length() -> None:
    metrics = gcode.parse(
        "M200 S1\nM83\n;FEATURE: Support\nG0 X0 Y0\nG1 X10 E100\n",
        densities=(1.24,),
    )
    assert metrics.filament_mm is None
    assert metrics.filament_mm_by_tool == (None,)
    assert metrics.material_cm3 == pytest.approx(0.1)
    assert metrics.support_mm3 == pytest.approx(100)
    assert metrics.grams() == pytest.approx(0.124)


def test_invalid_large_material_numbers_do_not_overflow() -> None:
    metrics = gcode.parse("; filament used [mm] = 1000\n", diameters=(1e308,))
    assert metrics.material_cm3 is None
    assert metrics.grams() is None
    metrics.resolved_filament_grams = (1e308, 1e308)
    assert metrics.grams() is None


def test_volumetric_diameter_changes_preserve_each_segments_volume_and_length() -> None:
    metrics = gcode.parse(
        "M83\nM200 D2\n;TYPE:Support\nG0 X0 Y0\nG1 X10 E100\nM200 D3\nG1 X20 E100\n",
        densities=(1.24,),
    )
    assert metrics.filament_mm == pytest.approx(100 / math.pi + 400 / (9 * math.pi))
    assert metrics.material_cm3 == pytest.approx(0.2)
    assert metrics.grams() == pytest.approx(0.248)


def test_volumetric_cura_placeholder_does_not_become_zero_when_diameter_is_unknown() -> None:
    metrics = gcode.parse(
        ";Filament used: 0m\nM200 S1\nM83\n;TYPE:Support\nG0 X0 Y0\nG1 X10 E100\n"
    )
    assert metrics.filament_mm is None
    assert metrics.filament_mm_by_tool == (None,)
    assert metrics.material_cm3 == pytest.approx(0.1)


PRUSA = """
; generated by PrusaSlicer 2.8.0 on 2026-07-28
; layer_height = 0.2
M83
;TYPE:Perimeter
G1 X10 Y10 E0.5
G1 X20 Y10 E0.5
;TYPE:Support material
G1 X30 Y10 E2.0
G1 X40 Y10 E2.0
;TYPE:Perimeter
G1 X50 Y10 E0.5
; filament used [mm] = 3420.5
; filament used [g] = 10.2
; total layer count = 145
; estimated printing time (normal mode) = 2h 14m 3s
"""

CURA = """
;Generated with Cura_SteamEngine 5.7.0
;LAYER_COUNT:88
;Layer height: 0.15
;TIME:4530
;Filament used: 3.42m
M82
;TYPE:WALL-OUTER
G1 X10 Y10 E1.0
;TYPE:SUPPORT
G1 X20 Y10 E3.0
G1 X30 Y10 E5.0
"""


# --- reading (§28.1) ----------------------------------------------------------------


@pytest.mark.parametrize(
    "moves",
    [
        "M83\nT0\nG1 X10 E100\nT2\nG1 X20 E200\n",
        "M82\nT0\nG92 E0\nG1 X10 E100\nT2\nG92 E0\nG1 X20 E200\n",
    ],
)
def test_used_tools_survive_missing_filament_comments(moves: str) -> None:
    """Die Aufteilung stammt aus den Werkzeugbewegungen, nie aus einer Gesamtlänge."""
    metrics = gcode.parse(moves)
    assert metrics.used_tools == (0, 2)
    assert metrics.filament_mm == pytest.approx(300.0)
    assert metrics.filament_mm_by_tool == pytest.approx((100.0, 0.0, 200.0))
    assert metrics.filament_mm_sources == ("motion", "motion", "motion")


def test_tool_selection_without_extrusion_does_not_invent_consumption() -> None:
    metrics = gcode.parse("T2\nG0 X10 Y10\nT0\nM83\nG1 X20 E100\n")
    assert metrics.used_tools == (0,)


@pytest.mark.parametrize("total", ["", "; total filament used [g] = 9.25\n"])
def test_all_filaments_contribute_to_the_print_metrics(total: str) -> None:
    """Listen sind Extruderwerte; die explizite Summe hat Vorrang."""
    metrics = gcode.parse(
        "; filament used [mm] = 0, 1000.5, 2000.25\n; filament used [g] = 0, 3.1, 6.15\n" + total
    )
    assert metrics.filament_mm == pytest.approx(3000.75)
    assert metrics.filament_grams == pytest.approx(9.25)
    assert metrics.filament_mm_by_tool == pytest.approx((0.0, 1000.5, 2000.25))
    assert metrics.filament_grams_by_tool == pytest.approx((0.0, 3.1, 6.15))


def test_an_explicit_material_total_wins_over_rounded_slot_values() -> None:
    metrics = gcode.parse("; filament used [g] = 3, 6\n; total filament used [g] = 9.25\n")
    assert metrics.filament_grams == pytest.approx(9.25)


@pytest.mark.parametrize("total_first", [False, True])
def test_tool_amounts_and_totals_survive_in_either_header_order(total_first: bool) -> None:
    """Die Gesamtsumme überschreibt weder Einzelwerte noch zählt sie doppelt."""
    tools = "; filament used [g] = 47, 6\n; filament used [mm] = 15500, 2000\n"
    totals = "; total filament used [g] = 53.1\n; total filament used [mm] = 17500.1\n"

    metrics = gcode.parse(totals + tools if total_first else tools + totals)

    assert metrics.filament_grams_by_tool == pytest.approx((47.0, 6.0))
    assert metrics.filament_mm_by_tool == pytest.approx((15500.0, 2000.0))
    assert metrics.filament_grams == pytest.approx(53.1)
    assert metrics.filament_mm == pytest.approx(17500.1)
    assert metrics.source == "gcode"


@pytest.mark.parametrize("missing", ["", "unknown", "-1", "nan", "inf", "1e309", "6invalid"])
def test_missing_tool_amounts_keep_their_position_and_never_become_a_total(missing: str) -> None:
    """Ein unbekannter Werkzeugplatz wird weder entfernt noch als null gezählt."""
    metrics = gcode.parse(
        f"; filament used [g] = 0, {missing}, 6\n; filament used [mm] = 0, {missing}, 2000\n"
    )

    assert metrics.filament_grams_by_tool == (0.0, None, 6.0)
    assert metrics.filament_mm_by_tool == (0.0, None, 2000.0)
    assert metrics.filament_grams is None
    assert metrics.filament_mm is None


def test_a_total_does_not_fill_a_missing_tool_amount() -> None:
    metrics = gcode.parse("; filament used [g] = 47, , 6\n; total filament used [g] = 60\n")

    assert metrics.filament_grams == pytest.approx(60.0)
    assert metrics.filament_grams_by_tool == (47.0, None, 6.0)


def test_a_missing_last_tool_is_preserved_and_no_number_is_invented() -> None:
    metrics = gcode.parse("; filament used [g] = 47, 6,\n")

    assert metrics.filament_grams_by_tool == (47.0, 6.0, None)
    assert metrics.filament_grams is None
    assert metrics.grams_by_tool() == (47.0, 6.0, None)


def test_an_empty_header_does_not_claim_a_tool_or_a_zero_amount() -> None:
    metrics = gcode.parse("; filament used [g] = \n; filament used [mm] = \n")

    assert metrics.filament_grams_by_tool == ()
    assert metrics.filament_mm_by_tool == ()
    assert metrics.filament_grams is None
    assert metrics.filament_mm is None


def test_two_finite_amounts_must_not_make_an_infinite_total() -> None:
    metrics = gcode.parse("; filament used [g] = 1e308, 1e308\n")

    assert metrics.filament_grams_by_tool == pytest.approx((1e308, 1e308))
    assert metrics.filament_grams is None


def test_a_total_alone_does_not_claim_tool_zero() -> None:
    metrics = gcode.parse("; total filament used [g] = 53\n; total filament used [mm] = 17500\n")

    assert metrics.filament_grams == pytest.approx(53.0)
    assert metrics.filament_mm == pytest.approx(17500.0)
    assert metrics.filament_grams_by_tool == ()
    assert metrics.filament_mm_by_tool == ()
    assert metrics.grams_by_tool(densities=(1.24,), diameters=(1.75,)) == ()


def test_a_single_tool_header_keeps_tool_zero() -> None:
    metrics = gcode.parse(PRUSA)

    assert metrics.filament_grams_by_tool == pytest.approx((10.2,))
    assert metrics.filament_mm_by_tool == pytest.approx((3420.5,))


def test_cura_tool_lengths_keep_their_units_and_unused_tools() -> None:
    metrics = gcode.parse("; Filament used: 0m, 0.047m, 0.006m\n")

    assert metrics.filament_mm_by_tool == pytest.approx((0.0, 47.0, 6.0))
    assert metrics.filament_mm == pytest.approx(53.0)


@pytest.mark.parametrize("amount", ["nan", "inf", "1e309", "-1", "53invalid"])
def test_invalid_explicit_totals_leave_valid_tool_values_usable(amount: str) -> None:
    metrics = gcode.parse(f"; total filament used [g] = {amount}\n; filament used [g] = 47, 6\n")

    assert metrics.filament_grams_by_tool == pytest.approx((47.0, 6.0))
    assert metrics.filament_grams == pytest.approx(53.0)


def test_tool_mass_conversion_needs_each_tools_density_and_diameter() -> None:
    metrics = gcode.parse("; filament used [mm] = 1000, 1000, 1000\n")

    assert metrics.grams_by_tool() == (None, None, None)
    assert metrics.grams_by_tool(densities=(1.0, 2.0, 3.0)) == (None, None, None)
    assert metrics.grams_by_tool(diameters=(2.0, 1.0, 1.75)) == (None, None, None)
    amounts = metrics.grams_by_tool(densities=(1.0, 2.0, None), diameters=(2.0, 1.0, 1.75))
    assert amounts[:2] == pytest.approx((3.141592653589793, 1.5707963267948966))
    assert amounts[2] is None


def test_explicit_tool_weights_including_zero_win_over_length_conversion() -> None:
    metrics = gcode.parse("; filament used [g] = 0, , 6\n; filament used [mm] = 1000, 1000, 1000\n")

    assert metrics.grams_by_tool(densities=(1.0, 1.0, 1.0), diameters=(2.0, 2.0, 2.0)) == (
        0.0,
        pytest.approx(3.141592653589793),
        6.0,
    )


@pytest.mark.parametrize("invalid", [0.0, -1.0, float("nan"), float("inf")])
def test_invalid_material_properties_do_not_turn_lengths_into_weights(invalid: float) -> None:
    metrics = gcode.parse("; filament used [mm] = 1000\n")

    assert metrics.grams_by_tool(densities=(invalid,), diameters=(1.75,)) == (None,)
    assert metrics.grams_by_tool(densities=(1.24,), diameters=(invalid,)) == (None,)


def test_a_prusa_file_gives_up_its_numbers() -> None:
    metrics = gcode.parse(PRUSA)

    assert "PrusaSlicer" in metrics.slicer
    assert metrics.print_seconds == pytest.approx(2 * 3600 + 14 * 60 + 3)
    assert metrics.filament_mm == pytest.approx(3420.5)
    assert metrics.filament_grams == pytest.approx(10.2)
    assert metrics.layer_count == 145
    assert metrics.layer_height == pytest.approx(0.2)


def test_a_cura_file_gives_up_its_numbers() -> None:
    """Andere Kommentare, dieselben Tatsachen — ein Muster je Tatsache, nicht
    eines je Slicer.
    """
    metrics = gcode.parse(CURA)

    assert "Cura" in metrics.slicer
    assert metrics.print_seconds == pytest.approx(4530.0)
    assert metrics.layer_count == 88
    assert metrics.filament_mm == pytest.approx(3420.0), "metres become millimetres"


def test_the_layer_count_is_counted_where_it_is_not_written() -> None:
    """PrusaSlicer nennt die Schichtzahl nicht immer — er markiert die Wechsel.

    Der Kopf einer echten Datei aus 2.9.6 trägt keine Gesamtzahl; im
    Prüfbericht stand deshalb bei jedem Prusa-Lauf nichts, wo bei Cura eine
    Zahl steht. Gezählte Marken sind dieselbe Auskunft.
    """
    without_header = """
; generated by PrusaSlicer 2.9.6 on 2026-08-20
;LAYER_CHANGE
G1 X10 Y10 E0.5
;LAYER_CHANGE
G1 X20 Y10 E0.5
;LAYER_CHANGE
G1 X30 Y10 E0.5
"""

    assert gcode.parse(without_header).layer_count == 3
    # Steht sie doch im Kopf, gilt die Aussage des Slicers — sie kennt auch
    # Schichten, die keine Bahn zeigen.
    assert gcode.parse(PRUSA).layer_count == 145


def test_what_is_not_in_the_file_stays_unknown() -> None:
    """Ein fehlender Wert fehlt, er ist nicht null — genau darum wird die
    Datei gelesen.

    Die Materiallänge steht hier trotzdem: eine Bahn mit Vorschub *ist* eine
    Aussage der Datei über das Filament, das durch sie ging. Zeit und
    Schichtzahl sagt nur der Kopf, und der schweigt.
    """
    metrics = gcode.parse("G1 X10 Y10 E1.0\n")

    assert metrics.print_seconds is None
    assert metrics.filament_mm == pytest.approx(1.0), "die Bahn sagt es, auch ohne Kopf"
    assert metrics.layer_count is None
    assert metrics.support_mm3 is None, "no type comments, no measured support"


def test_a_file_without_any_move_says_nothing_about_material() -> None:
    """Ohne Bahn und ohne Kopf bleibt die Länge unbekannt — nicht null."""
    metrics = gcode.parse(";FLAVOR:Marlin\nG28\nM104 S200\n")

    assert metrics.filament_mm is None


def test_curas_empty_header_does_not_become_a_measurement() -> None:
    """`CuraEngine` schreibt den Kopf, bevor es rechnet.

    Im Fenster füllt Cura „Filament used" nachträglich aus; von der
    Kommandozeile aus bleibt dort die Vorlage stehen. Gemessen an einem echten
    Lauf (5.13.0, 20-mm-Würfel): 1,8 MB Bahnen mit Vorschub, und im Kopf
    `Filament used: 0m`. Solidon meldete daraufhin null Meter und rechnete
    Kosten von null — die Datei selbst weiß es besser.
    """
    metrics = gcode.parse(
        ";Filament used: 0m\n;LAYER_COUNT:2\nM82\nG1 X10 Y10 E2.0\nG1 X20 Y10 E5.5\n"
    )

    assert metrics.filament_mm == pytest.approx(5.5)
    assert metrics.layer_count == 2, "was der Kopf sagt, gilt weiter"


def test_the_last_layer_mark_beats_the_header_time() -> None:
    """`;TIME:6666` ist Curas Vorlage, keine Zeit.

    Sie sieht mit 111 Minuten plausibel aus und steht für jedes Modell gleich
    da — auch für einen halb so hohen Würfel. Am Ende der Datei steht die
    gerechnete Zeit: gemessen 20,8 Minuten für einen 20-mm-Würfel, gegen 21 bei
    PrusaSlicer mit denselben Einstellungen.
    """
    metrics = gcode.parse(
        ";TIME:6666\n;LAYER:0\n;TIME_ELAPSED:45.96\n;LAYER:1\n;TIME_ELAPSED:1249.49\n"
    )

    assert metrics.print_seconds == pytest.approx(1249.49)


def test_a_stated_length_beats_the_moves() -> None:
    """Der Kopf kennt, was keine Bahn zeigt: Vorschieben, Reinigungsturm,
    Werkzeugwechsel. Wo er etwas sagt, gilt er."""
    metrics = gcode.parse(";filament used [mm] = 4000\nM82\nG1 X10 Y10 E2.0\n")

    assert metrics.filament_mm == pytest.approx(4000.0)


def test_a_short_length_in_millimetres_stays_millimetres() -> None:
    """Die Einheit steht in der Zeile — sie wird nicht aus der Größe geraten.

    Der Fund: ``metrics.filament_mm = number * 1000.0 if number < 100.0``. Ein
    kleines Teil mit 95 mm Faden wurde damit zu 95 Metern, aus 0,3 Gramm
    wurden 283, und die Gegenprobe gegen die Schätzung schlug Alarm. Die
    Größe einer Zahl sagt nichts über ihre Einheit; das Muster, das sie
    gefunden hat, sagt alles darüber.
    """
    metrics = gcode.parse("; filament used [mm] = 95\nM82\nG1 X10 Y10 E2.0\n")

    assert metrics.filament_mm == pytest.approx(95.0)


def test_metres_are_still_metres() -> None:
    """Die Gegenprobe: Cura schreibt Meter, und die werden umgerechnet."""
    metrics = gcode.parse("; Filament used: 0.095m\nM82\nG1 X10 Y10 E2.0\n")

    assert metrics.filament_mm == pytest.approx(95.0)


def test_the_support_volume_is_measured_not_guessed() -> None:
    """§28.1: gemessenes Stützmaterial — aus den Typ-Kommentaren und der
    E-Achse.
    """
    metrics = gcode.parse(PRUSA, diameters=(1.75,))

    assert metrics.support_mm3 is not None
    assert metrics.support_mm3 == pytest.approx(4.0 * gcode.FILAMENT_AREA, rel=1e-6)


def test_absolute_extrusion_is_counted_as_differences() -> None:
    metrics = gcode.parse(CURA, diameters=(1.75,))

    assert metrics.support_mm3 is not None
    # E läuft 1 → 3 → 5, mit dem Werkzeug auf Stützen für die letzten zwei Wege.
    assert metrics.support_mm3 == pytest.approx(4.0 * gcode.FILAMENT_AREA, rel=1e-6)


def test_an_m83_in_a_comment_does_not_switch_the_file_to_relative() -> None:
    """Der Fund: ``";" not in text or "M83" not in text``.

    Cura hängt seine Einstellungen als ``;SETTING_3``-Block ans Dateiende, und
    darin steht der Endcode der Maschine — mit ``M83``. Die Datei selbst
    fördert absolut, hatte aber keine Modus-Zeile vor der ersten Bahn: Aus
    einem Vorschub von 3 mm wurden 4, und bei einer echten Datei summiert sich
    jeder Wert der E-Achse statt der Differenzen. Gesucht wird deshalb der
    **Befehl** am Zeilenanfang, nicht die Zeichenfolge irgendwo im Text.
    """
    text = (
        ";Generated with Cura_SteamEngine 5.7.0\n"
        ";TYPE:WALL-OUTER\n"
        "G1 X10 Y10 E1.0\n"
        "G1 X20 Y10 E3.0\n"
        ";SETTING_3 machine_end_gcode = M104 S0 M83\n"
    )

    metrics = gcode.parse(text)

    assert metrics.filament_mm == pytest.approx(3.0), "absolut gezählt sind es die Differenzen"


def test_a_file_without_comments_still_finds_its_mode() -> None:
    """Die Gegenprobe von der anderen Seite: keine Kommentare, aber ``M83``.

    ``";" not in text`` hielt eine kommentarlose Datei für absolut. Hier
    rettete die Schleife den Fall, weil der Befehl vor den Bahnen steht — der
    Modus wird jetzt vor dem ersten Vorschub bestimmt und nicht aus dem
    Vorhandensein von Kommentaren geschlossen.
    """
    metrics = gcode.parse("M83\nG1 X10 Y10 E1.0\nG1 X20 Y10 E3.0\n")

    assert metrics.filament_mm == pytest.approx(4.0), "relativ gezählt ist es die Summe"


def test_an_m83_in_the_end_gcode_does_not_reach_back_to_the_first_line() -> None:
    """Derselbe Fund eine Stufe später — als **Befehl**, nicht als Kommentar.

    Der Docstring von ``_starts_absolute`` beschrieb das Fehlbild als behoben,
    und der Fall daneben prüfte es auch: ein ``M83`` in einem Kommentar am
    Dateiende. Gesucht wurde aber die erste Modus-Zeile der **ganzen** Datei,
    und die verbreitetste aller Redewendungen im Endcode ist genau ein
    ``M83`` mit einem Rückzug dahinter. Damit galt eine absolut fördernde
    Datei wieder als relativ, und die E-Werte summierten sich: gemessen 6,0 mm
    statt 3,0 mm für drei Bahnen mit E1, E2, E3.

    Entschieden wird deshalb im Text **vor** der ersten Bahn. Steht dort
    nichts, gilt absolut — die RepRap-Konvention und der Zustand jedes
    Druckers nach dem Einschalten.
    """
    text = "G1 X10 Y10 E1\nG1 X20 Y10 E2\nG1 X30 Y10 E3\nM83\nG1 E-3\n"

    metrics = gcode.parse(text)

    assert metrics.filament_mm == pytest.approx(3.0), (
        "der Endcode entscheidet nicht über den Anfang der Datei"
    )


def test_the_mode_before_the_first_path_still_counts() -> None:
    """Die Gegenprobe: derselbe Endcode, aber ``M83`` steht auch vorn.

    Ohne sie wäre die Regel „der Modus am Dateiende zählt nie", und daraus
    würde beim nächsten Nachbessern leicht „nur die erste Zeile zählt".
    Gemeint ist: was vor der ersten Bahn steht, entscheidet.
    """
    text = "M83\nG1 X10 Y10 E1\nG1 X20 Y10 E2\nG1 X30 Y10 E3\nM83\nG1 E-3\n"

    metrics = gcode.parse(text)

    assert metrics.filament_mm == pytest.approx(6.0), "relativ gezählt ist es die Summe"


def test_the_weight_follows_from_the_length() -> None:
    metrics = gcode.parse(CURA, diameters=(1.75,), densities=(1.24,))

    assert metrics.material_cm3 == pytest.approx(3420.0 * gcode.FILAMENT_AREA / 1000.0)
    assert metrics.grams() == pytest.approx(metrics.material_cm3 * gcode.DEFAULT_DENSITY)


def test_a_stated_weight_wins_over_the_computed_one() -> None:
    assert gcode.parse(PRUSA).grams() == pytest.approx(10.2)


def test_a_slicer_warning_travels_along() -> None:
    metrics = gcode.parse("; WARNING: Detected print stability issues\nG1 X1 E1\n")

    assert metrics.warnings == ("Detected print stability issues",)


# --- der Abgleich (§28.2) ------------------------------------------------------------


def test_a_close_estimate_says_nothing() -> None:
    check = gcode.compare(estimated=1000.0, measured=1050.0)

    assert check.within_limit
    assert check.findings == []


def test_a_far_estimate_becomes_a_finding() -> None:
    """§28.2: ein klarer Unterschied ist ein Befund — und ein Hinweis, §22 zu
    verbessern.
    """
    check = gcode.compare(estimated=500.0, measured=1000.0, what="support")

    assert not check.within_limit
    assert check.deviation == pytest.approx(0.5)
    assert check.findings[0].code == "gcode.deviation"
    assert check.findings[0].severity == "warning"
    assert "+50%" in str(check.findings[0].values["deviation"])


def test_the_estimate_is_never_replaced_by_the_measurement() -> None:
    """§22.5: beide bleiben, beide behalten ihre Herkunft. Nichts wird still überschrieben."""
    check = gcode.compare(estimated=500.0, measured=1000.0)

    assert check.estimated == 500.0
    assert check.measured == 1000.0
    assert check.findings[0].source == "gcode"


def test_every_measured_finding_says_it_was_measured() -> None:
    """§22.5: eine Schätzung und eine Messung sehen nie gleich aus."""
    metrics = gcode.parse(PRUSA)
    findings = gcode.findings_for(metrics)

    assert findings
    assert all(finding.source == "gcode" for finding in findings)
    codes = {finding.code for finding in findings}
    assert {"gcode.print_time", "gcode.material"} <= codes


def test_an_internal_finding_stays_internal() -> None:
    """Die andere Hälfte derselben Regel, von der anderen Seite geprüft."""
    import trimesh

    from app.core.geom.mesh import MeshData
    from app.core.slice.analysis import slice_body

    body = MeshData.of(trimesh.creation.box(extents=(20.0, 20.0, 10.0)))
    result = slice_body(body, 0.2)

    assert result.source == "internal"


def test_a_file_without_a_single_extrusion_is_not_a_print() -> None:
    """Cura schreibt bei fehlender Einstellung eine große Datei voller
    Leerfahrten und meldet trotzdem Erfolg. Gefragt wird an der Bewegung,
    nicht am Kommentar — sonst hinge die Antwort am Slicer.
    """
    leerlauf = """
;FLAVOR:Marlin
;TIME:6666
;Filament used: 0m
G0 X10 Y10
G1 X20 Y10 E0
G0 X30 Y10
"""
    assert not gcode.extrudes(leerlauf)
    assert gcode.extrudes(PRUSA)


# --- mehrere Platten (§25, §29) -----------------------------------------------


def test_two_plates_add_up_to_one_job() -> None:
    """Zeit und Material addieren sich, weil zweimal gedruckt wird."""
    first = gcode.GcodeMetrics(print_seconds=600.0, filament_mm=1000.0, filament_grams=10.0)
    second = gcode.GcodeMetrics(print_seconds=1200.0, filament_mm=2000.0, filament_grams=20.0)

    total = gcode.combine([first, second])

    assert total.print_seconds == 1800.0
    assert total.filament_mm == 3000.0
    assert total.filament_grams == 30.0
    assert total.source == "gcode"


def test_tool_numbers_from_different_plates_do_not_claim_the_same_spool() -> None:
    first = gcode.parse("; filament used [g] = 47, 6\n; filament used [mm] = 1000, 200\n")
    second = gcode.parse("; filament used [g] = 12, 3\n; filament used [mm] = 300, 100\n")

    total = gcode.combine([first, second])

    assert total.filament_grams == pytest.approx(68.0)
    assert total.filament_mm == pytest.approx(1600.0)
    assert total.filament_grams_by_tool == ()
    assert total.filament_mm_by_tool == ()
    assert first.filament_grams_by_tool == pytest.approx((47.0, 6.0))
    assert second.filament_grams_by_tool == pytest.approx((12.0, 3.0))


def test_a_missing_value_on_one_plate_leaves_the_sum_missing() -> None:
    """Sonst stünde eine Gesamtzeit da, die zu kurz ist — und niemand sähe es.

    Dieselbe Unterscheidung, aus der ``GcodeMetrics`` seine Felder optional
    führt: ein fehlender Wert fehlt, er ist nicht null.
    """
    first = gcode.GcodeMetrics(print_seconds=600.0, filament_grams=10.0)
    second = gcode.GcodeMetrics(filament_grams=20.0)

    total = gcode.combine([first, second])

    assert total.print_seconds is None
    assert total.filament_grams == 30.0


def test_the_layer_count_belongs_to_a_plate_and_not_to_a_job() -> None:
    """Über zwei Platten addiert wäre sie eine Zahl, die es nirgends gibt."""
    plates = [gcode.GcodeMetrics(layer_count=110), gcode.GcodeMetrics(layer_count=40)]

    assert gcode.combine(plates).layer_count is None
    # Bei einer Platte bleibt sie, denn dort sagt sie etwas.
    assert gcode.combine(plates[:1]).layer_count == 110


def test_one_plate_comes_back_unchanged() -> None:
    """Der einfarbige Einzelauftrag ist der Sonderfall mit einem Eintrag,
    nicht ein anderer Weg."""
    only = gcode.parse(PRUSA)

    assert gcode.combine([only]) is only
    assert gcode.combine([]) == gcode.GcodeMetrics()


def test_a_zero_measurement_is_not_a_perfect_match() -> None:
    """`deviation` gab für `measured=0` glatt null zurück — die größtmögliche
    Abweichung sah aus wie die perfekte Übereinstimmung. Eine Null ist keine
    Messung, sondern „nicht vergleichbar" (Regel 14)."""
    check = gcode.compare(12.0, 0.0, "material")

    assert [entry.code for entry in check.findings] == ["gcode.no_measurement"]
    assert all(entry.code != "gcode.deviation" for entry in check.findings)


def test_the_finding_without_a_measurement_carries_the_origin_of_its_number() -> None:
    """Regel 14: Der einzige Zahlenwert darin ist die **Schätzung**.

    Der Befund trug ``source="gcode"``, weil er beim Lesen des G-Code
    entsteht — und stellte damit eine interne Zahl als gemessene aus. Genau
    die Verwechslung, die §22.5 verbietet: Die Datei nennt hier keinen
    Messwert, das ist ja der Anlass des Befunds.
    """
    check = gcode.compare(12.0, 0.0, "material")

    finding = check.findings[0]
    assert finding.source == "internal"
    assert "estimated" in finding.values


def test_a_zero_gram_header_remains_authoritative_over_the_length() -> None:
    """Dieselbe explizite Null gilt in Ergebnisanzeige und Lagerbuchung."""
    metrics = gcode.GcodeMetrics(filament_mm=1000.0, filament_grams=0.0)

    grams = metrics.grams(density=1.24)

    assert grams == pytest.approx(0.0)


def test_mass_conversion_uses_the_explicit_filament_diameter() -> None:
    metrics = gcode.GcodeMetrics(filament_mm=1000.0)
    assert metrics.grams(density=1.2, diameter=2.85) == pytest.approx(7.655276)
    assert metrics.grams(density=None, diameter=2.85) is None
    assert metrics.grams(density=1.2, diameter=None) is None


def test_multiple_unresolved_tools_never_use_one_global_material() -> None:
    metrics = gcode.GcodeMetrics(filament_mm=3000, filament_mm_by_tool=(1000, 2000))
    assert metrics.grams(density=1.2, diameter=2.85) is None
    metrics.resolved_filament_grams = (7.655276, 5.965099)
    assert metrics.grams(density=9, diameter=9) == pytest.approx(13.620375)
    metrics.resolved_filament_grams = (7.655276, None)
    assert metrics.grams(density=9, diameter=9) is None


@pytest.mark.parametrize("explicit_total", [False, True])
@pytest.mark.parametrize("from_paths", [False, True])
def test_partial_tool_weights_do_not_appear_as_a_complete_total(
    explicit_total: bool, from_paths: bool
) -> None:
    text = "; filament used [g] = 47\n"
    text += (
        "M83\nT0\nG1 X10 E100\nT2\nG1 X20 E200\n"
        if from_paths
        else "; filament used [mm] = 1000, 2000\n"
    )
    if explicit_total:
        text += "; total filament used [g] = 53\n"
    metrics = gcode.parse(text)
    assert metrics.filament_grams_by_tool == (47.0,)
    if explicit_total:
        assert metrics.grams() == pytest.approx(53.0)
    else:
        assert metrics.grams() is None


def test_combined_plates_keep_their_resolved_material_weights() -> None:
    first = gcode.GcodeMetrics(filament_mm=1000, resolved_filament_grams=(7.655276,))
    second = gcode.GcodeMetrics(filament_mm=2000, resolved_filament_grams=(5.965099,))
    assert gcode.combine([first, second]).grams(9, 9) == pytest.approx(13.620375)
    second.resolved_filament_grams = (None,)
    assert gcode.combine([first, second]).grams(9, 9) is None


def test_material_finding_never_assumes_properties_for_an_unresolved_file() -> None:
    metrics = gcode.GcodeMetrics(filament_mm=1000)
    assert not any(finding.code == "gcode.material" for finding in gcode.findings_for(metrics))
    metrics.resolved_filament_grams = (7.655276,)
    material = next(
        finding for finding in gcode.findings_for(metrics) if finding.code == "gcode.material"
    )
    assert material.values["grams"] == pytest.approx(7.7)


# --- wohin die Datei wirklich druckt (§29) -------------------------------------

#: Ein Anfang, wie der ElegooSlicer ihn schreibt: die Reinigung steht **vor**
#: der ersten Schicht und 1,2 mm vor dem Bett, das dieselbe Datei nennt.
ELEGOO_START = """
; printable_area = 0x0,256x0,256x256,0x256
; printable_height = 256
G90
M83
G1 X127 Y-1.2 F20000
G1 Z0.5 F900
G92 E0 ;Reset Extruder
G1 E6 F120
G1 X87 E20 F1200
;LAYER_COUNT:2
;LAYER:0
G1 Z0.2
G0 X120 Y120
G1 X120 Y120 E0.5
G1 X136 Y136 E0.5
"""


def test_the_start_code_of_the_machine_is_not_the_print() -> None:
    """Zwei Gründe, aus denen dieselbe Datei sonst 1,2 mm neben der Platte
    druckt — und beide sind gemessen, nicht gedacht.

    ``G1 E6 F120`` fördert sechs Millimeter, ohne einen zu fahren: das ist die
    Reinigung, keine Bahn. Und ``G1 X87 E20`` **fährt** dabei, liegt aber vor
    der ersten Schicht — es ist der Startcode des Maschinenprofils, den die
    Orca-Familie aus ihrem eigenen Bestand mitbringt und den Solidon nicht
    beurteilt (§29).

    Übrig bleibt das Modell: zwei Bahnen um die Bettmitte.
    """
    box = gcode.printed_extent(ELEGOO_START)

    assert box is not None
    assert box.minimum[:2] == (120.0, 120.0), "die Reinigungsbahn zählt nicht mit"
    assert box.maximum[:2] == (136.0, 136.0)


def test_without_a_layer_mark_everything_counts() -> None:
    """Die Gegenprobe: Wo keine Schichtmarke steht, gibt es auch keinen
    Startcode zum Abtrennen — dann wird die ganze Datei gemessen."""
    ohne_marke = "\n".join(
        line for line in ELEGOO_START.splitlines() if not line.startswith(";LAYER")
    )

    box = gcode.printed_extent(ohne_marke)

    assert box is not None
    assert box.minimum[1] == pytest.approx(-1.2), "jetzt zählt die Reinigungsbahn mit"


def test_a_purge_without_movement_is_never_a_path() -> None:
    """Und die zweite Hälfte einzeln: eine Förderung ohne Fahrweg ist keine
    Bahn, gleich wo sie steht (dieselbe Bedingung wie in ``extrudes``)."""
    stehend = "G90\nG1 X50 Y-9 F9000\nG1 E12 F120\n"

    assert gcode.printed_extent(stehend) is None


def test_a_moving_purge_before_the_first_layer_is_not_a_model_print() -> None:
    purge_only = "G90\nM83\nG1 X87 Y-1.2 E20\n;LAYER:0\nG0 X10 Y10 Z0.2\n"

    assert not gcode.extrudes(purge_only)
    assert gcode.printed_extent(purge_only) is None


def test_the_first_printed_segment_includes_its_start() -> None:
    text = "G90\nM83\n;LAYER:0\nG0 X-5 Y0 Z0.2\nG1 X5 Y0 E1\n"

    box = gcode.printed_extent(text)

    assert box is not None
    assert box.minimum[0] == pytest.approx(-5.0)
    assert box.maximum[0] == pytest.approx(5.0)


def test_an_absolute_retraction_does_not_enlarge_the_printed_extent() -> None:
    text = "G90\nM82\nG92 E0\n;LAYER:0\nG0 X0 Y10 Z0.2\nG1 X10 Y10 E10\nG1 X300 Y10 E9\n"

    box = gcode.printed_extent(text)

    assert box is not None
    assert box.maximum[0] == pytest.approx(10.0)


def test_a_full_circle_arc_counts_as_extrusion_with_its_whole_extent() -> None:
    text = "G90\nM83\n;LAYER:0\nG0 X10 Y0 Z0.2\nG2 X10 Y0 I-10 J0 E1\n"

    box = gcode.printed_extent(text)
    metrics = gcode.parse(text)

    assert gcode.extrudes(text)
    assert metrics.filament_mm == pytest.approx(1.0)
    assert box is not None
    assert box.minimum[:2] == pytest.approx((-10.0, -10.0))
    assert box.maximum[:2] == pytest.approx((10.0, 10.0))


def test_the_arc_centre_mode_does_not_change_the_axis_mode() -> None:
    """G91.1 steuert I/J, nicht die Koordinaten von X/Y/Z."""
    text = "G90\nM83\n;LAYER:0\nG0 X10 Y0 Z0.2\nG91.1\nG1 X20 Y0 E1\n"

    box = gcode.printed_extent(text)

    assert box is not None
    assert box.minimum[0] == pytest.approx(10.0)
    assert box.maximum[0] == pytest.approx(20.0)


def test_absolute_arc_centres_are_measured_in_their_own_mode() -> None:
    """G90.1 macht I/J absolut, während X/Y durch G90 absolut bleiben."""
    text = "G90\nM83\n;LAYER:0\nG0 X10 Y0 Z0.2\nG90.1\nG3 X20 Y10 I10 J10 E1\n"

    box = gcode.printed_extent(text)

    assert box is not None
    assert box.minimum[:2] == pytest.approx((10.0, 0.0))
    assert box.maximum[:2] == pytest.approx((20.0, 10.0))


def test_streaming_keeps_the_metric_pattern_priority() -> None:
    """Die frühere Zeile schlägt kein höher priorisiertes Format."""
    analysis = gcode.analyze_lines(
        iter(("; TIME:30\n", "; estimated printing time (normal mode) = 1h 2m 3s\n"))
    )

    assert analysis.metrics.print_seconds == pytest.approx(3723.0)


def test_streaming_stops_between_two_lines_when_cancelled() -> None:
    """Auch das Rücklesen einer großen Druckdatei bleibt jederzeit abbrechbar."""
    from app.core.errors import OperationCancelled
    from app.core.scene.cancel import CancelSignal

    signal = CancelSignal()
    consumed = 0

    def lines():
        nonlocal consumed
        consumed += 1
        yield "G90\n"
        signal.cancel()
        consumed += 1
        yield "G1 X1 Y1 E1\n"
        consumed += 1
        yield "G1 X2 Y2 E1\n"

    with pytest.raises(OperationCancelled):
        gcode.analyze_lines(lines(), cancelled=signal)

    assert consumed == 2, "nach dem Abbruch darf keine weitere Zeile gelesen werden"


def test_the_file_says_which_bed_it_printed_on() -> None:
    """Die einzige Auskunft, die vom Slicer selbst kommt.

    Gemessen an den drei Familien: die Orca-Familie schreibt
    ``printable_area`` und ``printable_height``, PrusaSlicer ``bed_shape``
    und ``max_print_height``, CuraEngine keines von beiden. Gegen Solidons
    eigenen Bauraum zu messen hieße bei den ersten zwei, eine Abweichung
    zwischen zwei Maschinenprofilen als Druckfehler zu melden.
    """
    orca = gcode.stated_bed(ELEGOO_START)
    prusa = gcode.stated_bed(
        "; bed_shape = -110x-110,110x-110,110x110,-110x110\n; max_print_height = 250\n"
    )

    assert orca is not None
    assert (orca.minimum, orca.maximum) == ((0.0, 0.0, 0.0), (256.0, 256.0, 256.0))
    assert prusa is not None
    assert (prusa.minimum, prusa.maximum) == ((-110.0, -110.0, 0.0), (110.0, 110.0, 250.0))
    assert gcode.stated_bed(CURA) is None, "CuraEngine schreibt seine Bettform nicht"
