"""Das Register der Operationen (Bauplan §10): die eine Deklaration, die jede
Oberfläche liest."""

from app.core.registry.params import (
    GATHERED_KINDS,
    json_schema,
    op_params,
    param,
    validate,
)
from app.core.registry.registry import (
    CATEGORIES,
    FEATURE_KINDS,
    MENU_GROUPS,
    MENU_TWINS,
    REGISTRY,
    TWIN_TOGGLES,
    VARIABLE,
    MenuSection,
    OperationSpec,
    Registry,
    group_title,
    register_op,
)
from app.core.registry.surfaces import (
    MAX_MENU_ROWS,
    CliArgument,
    CliCommand,
    PaletteEntry,
    caveat_line,
    cli_commands,
    context_menu,
    documentation,
    group_is_flat,
    menu_path,
    menu_tree,
    palette_entries,
    tool_schemas,
)

__all__ = [
    "CATEGORIES",
    "FEATURE_KINDS",
    "GATHERED_KINDS",
    "MAX_MENU_ROWS",
    "MENU_GROUPS",
    "MENU_TWINS",
    "REGISTRY",
    "TWIN_TOGGLES",
    "VARIABLE",
    "CliArgument",
    "CliCommand",
    "MenuSection",
    "OperationSpec",
    "PaletteEntry",
    "Registry",
    "caveat_line",
    "cli_commands",
    "context_menu",
    "documentation",
    "group_is_flat",
    "group_title",
    "json_schema",
    "menu_path",
    "menu_tree",
    "op_params",
    "palette_entries",
    "param",
    "register_op",
    "tool_schemas",
    "validate",
]
