"""Welche Aufzählungswerte Anycubic Slicer Next annimmt — Rundreise über die Druckdatei.

Je Lauf bekommt jeder Schlüssel einen Kandidaten in den sonst leeren Prozess;
was im Konfigurationsblock zurückkommt, ist angenommen, ein anderer Wert ist
umgedeutet. Kandidaten: alle Werte, die die vier übrigen Orca-Programme in
``tests/data/slicer_values.json`` führen, samt ihren umgedeuteten.
Aufruf aus der Wurzel: .venv/Scripts/python.exe .claude/.state/anycubic-2026-10-05/aufzaehlungen.py <ausgabeordner>
"""

import json
import subprocess
import sys
from pathlib import Path

import trimesh

from app.core.export import slicer_profiles as sp

OUT = Path(sys.argv[1])
EXE = Path(r"C:\Program Files\AnycubicSlicerNext\AnycubicSlicerNext.exe")
measured = json.loads(Path("tests/data/slicer_values.json").read_text(encoding="utf-8"))["programs"]
candidates: dict[str, list[str]] = {}
for program in ("orcaslicer", "elegooslicer", "bambustudio", "crealityprint"):
    entry = measured[program]
    for key, values in entry["values"].items():
        bucket = candidates.setdefault(key, [])
        bucket.extend(value for value in values if value not in bucket)
    for key, changed in entry.get("unknown", {}).items():
        bucket = candidates.setdefault(key, [])
        bucket.extend(value for value in changed if value not in bucket)
OUT.mkdir(parents=True, exist_ok=True)
cube = OUT / "wuerfel.stl"
trimesh.creation.box(extents=(20, 20, 20)).apply_translation((125, 125, 10)).export(cube)
everything = sp.find_profiles(EXE, "orca", ("machine", "process", "filament"))
roots = sp.profile_roots("orca", EXE)
machine = next(e for e in everything if e.kind == "machine" and e.name == "Anycubic Kobra S1 0.4 nozzle")
filament = sp.match_filament(everything, machine, "PLA", roots)
machine_doc = {"type": "machine", "from": "system", "instantiation": "true", **sp.resolve_profile(machine, roots)}
machine_doc["name"] = "Probe Maschine"
filament_doc = {"type": "filament", "from": "User", "instantiation": "true", **sp.resolve_profile(filament, roots)}
filament_doc["name"] = "Probe Filament"
(OUT / "machine.json").write_text(json.dumps(machine_doc, indent=1), encoding="utf-8")
(OUT / "filament.json").write_text(json.dumps(filament_doc, indent=1), encoding="utf-8")
accepted: dict[str, list[str]] = {}
changed: dict[str, dict[str, str]] = {}
rounds = max(len(values) for values in candidates.values())
for index in range(rounds):
    work = OUT / f"lauf-{index:02d}"
    work.mkdir(exist_ok=True)
    asked = {key: values[index] for key, values in candidates.items() if index < len(values)}
    process = {
        "type": "process",
        "from": "system",
        "instantiation": "true",
        "name": "Probe",
        "compatible_printers": ["Probe Maschine"],
        **asked,
    }
    (work / "process.json").write_text(json.dumps(process, indent=1), encoding="utf-8")
    command = [
        str(EXE), "--load-settings", f"{OUT / 'machine.json'};{work / 'process.json'}",
        "--load-filaments", str(OUT / "filament.json"), "--slice", "0", "--outputdir", str(work), str(cube),
    ]
    run = subprocess.run(command, capture_output=True, text=True, errors="replace", timeout=900)
    gcodes = sorted(work.glob("*.gcode"))
    if not gcodes:
        print("Lauf", index, "ohne Druckdatei, Exit", run.returncode, run.stdout[-400:])
        continue
    block = {}
    for line in gcodes[-1].read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("; ") and " = " in line:
            key, _eq, value = line[2:].partition(" = ")
            block[key.strip()] = value.strip()
    for key, value in asked.items():
        found = block.get(key)
        if found == value:
            accepted.setdefault(key, []).append(value)
        else:
            changed.setdefault(key, {})[value] = found
    print("Lauf", index, "Exit", run.returncode, "Schlüssel", len(asked))
result = {
    "version": next(
        (line[2:].strip() for line in gcodes[-1].read_text(encoding="utf-8", errors="replace").splitlines() if line.startswith("; generated by")),
        "",
    ),
    "values": {key: sorted(values) for key, values in sorted(accepted.items())},
    "unknown": changed,
}
(OUT / "aufzaehlungen.json").write_text(json.dumps(result, indent=1, ensure_ascii=False), encoding="utf-8")
print(json.dumps(result, indent=1, ensure_ascii=False))
